### ISSUE TITLE
when signmultisigtx with -s option,ucd crashed[bug]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#103]
Yangs-MacBook-Pro:bin cary$ ./ucd
20181201T145646 INFO [ucd] Ucd version is 0.0.2
20181201T145646 INFO [ucd] Using config file: "/Users/cary/Library/Application Support/UChain/uc.conf"
20181201T145646 INFO [ucd] Please wait while the server is starting...
20181201T145646 INFO [node] Starting manual session.
20181201T145646 INFO [network] Contacting seed [192.168.16.169:5682]
20181201T145646 INFO [network] Failure contacting seed [192.168.16.169:5682] operation failed
20181201T145646 INFO [ucd] Seeding is complete.
20181201T145646 INFO [http] Http Service listen on 0.0.0.0:8820
20181201T145646 INFO [mgserver] Websocket Service listen on 0.0.0.0:8821
20181201T145646 INFO [network] session_seed complete!
20181201T145646 INFO [node] Node start height is (11598).
20181201T145646 INFO [node] Starting inbound session.
20181201T145646 INFO [node] Starting outbound session.
20181201T145646 INFO [ucd] Bound public query service to tcp://*:18707
20181201T145646 INFO [ucd] Server is started.
20181201T145654 INFO [upnp] No valid UPnP IGDs found
20181201T145847 INFO [network] Contacting seed [192.168.16.169:5682]
20181201T145848 INFO [network] Failure contacting seed [192.168.16.169:5682] operation failed
20181201T145851 INFO [network] session_seed complete!
Segmentation fault: 11

./uc-cli signmultisigtx yang 123456 04000000011033078d7a8349ed4cd8dcd1d816e44c7679aaa9c43573678dc54c4bf92f3adf00000000b4004730440220558d17117161eea5e86f5fc0c21f1d00a6810241e3f669a32fedd5601c356150022006ac2e9719c56c87f295dd1026eae9cc6b95fc9b892e3a91f5c517d80ceae950014c6952210260e2c278e4d45ec11e60d7048da7563e178baf3464b5829c9c28af146a2ad46f21026c05f0fe5306fc9c5282600f09305199da99664a6a90f430b59fae8b09cc7aeb2103bec77692da62f861065c04d09de5b217c14be033453a9235a1c67853cccf3ea953aeffffffff0210270000000000001976a91465a28a57f631d6d6da1a0036e72942a60b95743d88ac010000000000000020f40e000000000017a9147d23f7085143c701e1fa64224fb7ff6781a67edd87010000000000000000000000 -s 0260e2c278e4d45ec11e60d7048da7563e178baf3464b5829c9c28af146a2ad46f

**Comment by yangguanglu** [comment]
{
                "address" : "3D6hUQszXSMZPKTsSdD32jRUF5xkbPd8dQ",
                "description" : "",
                "index" : 2,
                "m" : 2,
                "multisig_script" : "2 [ 0260e2c278e4d45ec11e60d7048da7563e178baf3464b5829c9c28af146a2ad46f ]  [ 026c05f0fe5306fc9c5282600f09305199da99664a6a90f430b59fae8b09cc7aeb ]  [ 03bec77692da62f861065c04d09de5b217c14be033453a9235a1c67853cccf3ea9 ] 3 checkmultisig",
                "n" : 3,
                "public_keys" :
                [
                        "0260e2c278e4d45ec11e60d7048da7563e178baf3464b5829c9c28af146a2ad46f",
                        "026c05f0fe5306fc9c5282600f09305199da99664a6a90f430b59fae8b09cc7aeb",
                        "03bec77692da62f861065c04d09de5b217c14be033453a9235a1c67853cccf3ea9"
                ],
                "self_publickey" : "026c05f0fe5306fc9c5282600f09305199da99664a6a90f430b59fae8b09cc7aeb"
        }

**Comment by yangguanglu** [comment]
@yuyuyu2018 fixed 466e5b565063e0eaf797f1249d6055dee92c8b29

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
