### ISSUE TITLE
Windows only addpeer one.【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#107]

**Comment by UmckaBear** [comment]
Also there additional limitation with parameters - 4 addresses = error, less - no error message

> E:\Uchain\UChain_UIP0.2.windows\bin>uc-cli.exe addpeer -o add 112.74.181.29:5682 1.1.1.1:8000 1.1.1.1:122 13.124.250.27:5682
> {
>         "code" : 1021,
>         "message" : "too many positional options have been specified on the command line"
> }
> 
> E:\Uchain\UChain_UIP0.2.windows\bin>uc-cli.exe addpeer -o add 112.74.181.29:5682  1.1.1.1:8000 13.124.250.27:5682
> success

**Comment by o-u-p** [comment]
Please refer the doc [https://github.com/UCHAIN-WORLD/uchain-fullnode/wiki/system#addpeer](url) ,only one peer can be added once.

**Comment by o-u-p** [comment]
It has been fixed @yuyuyu2018 .

**Comment by yuyuyu2018** [comment]
After verification does not solve the  problem

**Comment by yuyuyu2018** [comment]
Tips need to be modified
tony@ubuntu:~/project/uchain-fullnode/build/bin$ ./uc-cli addpeer -o add 112.74.181.29:5682 1.1.1.1:8000 1.1.1.1:122 13.124.250.27:5682
{
	"code" : 1021,
	"message" : "too many positional options have been specified on the command line"
}
tony@ubuntu:~/project/uchain-fullnode/build/bin$ ./uc-cli addpeer -o add  1.1.1.1:8000 1.1.1.1:122 13.124.250.27:5682
success
tony@ubuntu:~/project/uchain-fullnode/build/bin$ ./uc-cli showpeers
[
	"116.62.238.230:5682",
	"112.74.181.29:5682",
	"120.78.209.248:5682",
	"192.168.16.211:57200",
	"35.182.225.90:5682",
	"13.124.250.27:5682",
	"192.168.16.211:5682",
	"192.168.16.128:5682",
	"192.168.16.128:50578"
]
@o-u-p

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved.
