### ISSUE TITLE
Failed to send vote to black hole address【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#110]
[root@localhost bin]# ./uc-cli sendtokenfrom snake02 123456 UcuW7wVu198Nuzok8eeMDUNEZQoGqQRRz5  1111111111111111111114oLvT2  VOTE 1
{
	"code" : 5012,
	"message" : "Cannot send 'VOTE' token in this way.Please use vote command."
}

**Comment by o-u-p** [comment]
It is rule of VOTE token, please check it @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
destroy VOTE token need to use vote commond
