### ISSUE TITLE
mongoose_listen is error in uc.conf  【bug】

### ISSUE THREAD

**Issue by snake0126** [UCHAIN-WORLD/uchain-fullnode#112]
uc.conf
[server]
log_level = DEBUG
mongoose_listen = 0.0.0.0:8820

[root@mainnet-ali-sz-01 uchain]# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:56000           0.0.0.0:*               LISTEN      2302/sshd           
tcp        0      0 0.0.0.0:10050           0.0.0.0:*               LISTEN      23129/zabbix_agentd 
tcp        0      0 127.0.0.1:28707         0.0.0.0:*               LISTEN      17637/./ucd         
tcp        0      0 127.0.0.1:8707          0.0.0.0:*               LISTEN      17637/./ucd         
tcp        0      0 0.0.0.0:18707           0.0.0.0:*               LISTEN      17637/./ucd         
tcp6       0      0 :::10050                :::*                    LISTEN      23129/zabbix_agentd 
tcp6       0      0 :::5682                 :::*                    LISTEN      17637/./ucd 

[root@mainnet-ali-sz-01 bin]# ps -ef | grep ucd
root     17637     1  0 Dec05 ?        00:12:29 ./ucd -c /data/ucd/conf/uc.con

uc.conf  port is 8820
port 8820 not use to ucd

**Comment by o-u-p** [comment]
Use relative path instead of absolute path.

**Comment by o-u-p** [comment]
Change to absolute path, please check in windows_tony branch @yuyuyu2018 .

**Comment by o-u-p** [comment]
ucd and uc-cli both add -c option, please test in windows_tony branch @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved.
