### ISSUE TITLE
[UChain Testnet UIP0.2] Full node runs under "mainnet" folder and with "testnet" parameter set to false [bug]

### ISSUE THREAD

**Issue by igrekm** [UCHAIN-WORLD/uchain-fullnode#114]
As I want to run some tests on the testnet, I want to be able to check if I'm running on mainnet or testnet. 

During the first initialization, the full node release creates "mainnet" folder in the file system and runs with testnet parameter set to "false".

This is misleading for the testnet beta testing. Either the node is actually running on mainnet and new release should be issued for testnet testing nor this is a label and setting issue and the node is connected to a testnet.

Currently, based on showinfo command line output, I'm not able to know if I'm running on testnet or mainnet.

Full nodes were downloaded from: https://github.com/UCHAIN-WORLD/uchain-fullnode/releases

Tested on both Windows and Linux releases with similar results and observations.

First initialization log output: 

20181209T181205 INFO [ucd] Ucd version is 0.0.2
20181209T181205 INFO [ucd] Using config file: "/home/ec2-user/.UChain"
20181209T181205 INFO [ucd] Please wait while initializing "/home/ec2-user/.UChain/mainnet"
directory...
20181209T181400 INFO [ucd] Completed initialization.
20181209T181400 INFO [ucd] Please wait while the server is starting...
20181209T181400 INFO [node] Starting manual session.
20181209T181400 INFO [network] Contacting seed [main-uchain-a.live:5682]
20181209T181400 INFO [network] Contacting seed [main-uchain-b.live:5682]
20181209T181400 INFO [network] Contacting seed [35.182.225.90:5682]
20181209T181400 INFO [network] Contacting seed [13.124.250.27:5682]
20181209T181400 INFO [network] Contacting seed [112.74.181.29:5682]
20181209T181400 INFO [network] Contacting seed [120.78.209.248:5682]
20181209T181400 INFO [network] Contacting seed [116.62.238.230:5682]
20181209T181400 INFO [network] Failure contacting seed [main-uchain-a.live:5682] resolving
hostname failed
20181209T181400 INFO [network] Failure contacting seed [main-uchain-b.live:5682] resolving
hostname failed
20181209T181401 INFO [network] Connected seed [35.182.225.90:5682] as
35.182.225.90:5682
20181209T181401 INFO [network] Connected seed [13.124.250.27:5682] as
13.124.250.27:5682
20181209T181401 INFO [network] Connected seed [116.62.238.230:5682] as
116.62.238.230:5682
20181209T181401 INFO [network] Connected seed [120.78.209.248:5682] as
120.78.209.248:5682
20181209T181401 INFO [network] Connected seed [112.74.181.29:5682] as
112.74.181.29:5682
20181209T181401 INFO [network] Seed channel stopped: channel is stopped
20181209T181401 INFO [network] Seed channel stopped: channel is stopped
20181209T181401 INFO [network] Seed channel stopped: channel is stopped
20181209T181401 INFO [network] Seed channel stopped: channel is stopped
20181209T181402 INFO [ucd] Seeding is complete.
20181209T181402 INFO [network] session_seed complete!
20181209T181402 INFO [network] Seed channel stopped: channel is stopped
20181209T181402 INFO [node] Node start height is (0).
20181209T181402 INFO [node] Starting inbound session.
20181209T181402 INFO [node] Starting outbound session.
20181209T181402 INFO [ucd] Bound public query service to tcp://*:18707
20181209T181402 INFO [ucd] Server is started.
20181209T181402 INFO [http] Http Service listen on 127.0.0.1:8707
20181209T181402 INFO [mgserver] Websocket Service listen on 127.0.0.1:28707
20181209T181408 INFO [upnp] No valid UPnP IGDs found

Showinfo output once full node is running

$ ./uc-cli showinfo
[
{
"database_version" : "0.0.2",
"height" : 21018,
"is_mining" : false,
"miner-count" : 3,
"peers" : 5,
"protocol_version" : 70012,
"testnet" : false,
"token_count" : 2,
"wallet_account_count" : 1,
"wallet_version" : "0.0.2"
}
]

Full node connected to the following peers:
$ ./uc-cli showpeers
[
"35.182.225.90:5682",
"13.124.250.27:5682",
"116.62.238.230:5682",
"120.78.209.248:5682",
"112.74.181.29:5682"
]

**Comment by o-u-p** [comment]
Since I all know that's testnet, we will remove the "testnet" parameter temporarily.

**Comment by o-u-p** [comment]
Please test @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
After verification, the "testnet" parameter have been removed
