### ISSUE TITLE
command description error[bug]

### ISSUE THREAD

**Issue by Evame19** [UCHAIN-WORLD/uchain-fullnode#117]
PS E:\Uchain\UChain_UIP0.2.windows\bin> $ uc-cli showbalance rtewret 67tyrt56D
$ : Имя "$" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность
 написания имени, а также наличие и правильность пути, после чего повторите попытку.
строка:1 знак:1
+ $ uc-cli showbalance rtewret 67tyrt56D
+ ~
    + CategoryInfo          : ObjectNotFound: ($:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
Incorrectly written command code. Instead of "$ uc-cli showbalance" you need to write "./uc-cli showbalance".
![bug](https://user-images.githubusercontent.com/41598354/49770174-e38d4300-fceb-11e8-8329-ac6073fcf4db.jpg)

**Comment by o-u-p** [comment]
It's windows default behavior, '$'  is used in unix system to represent the environment variable.

**Comment by Evame19** [comment]
I understand that writing correctly './'. But in the list of commands you have a '$' sign, and this can be confusing to some users. Please correct this.

**Comment by yuyuyu2018** [comment]
no problem
