### ISSUE TITLE
The command shutdown for Windows[requirement]

### ISSUE THREAD

**Issue by UmckaBear** [UCHAIN-WORLD/uchain-fullnode#125]
The command shutdown or alternative should be added for Windows. If not required, notice should be added in Wiki how to stop correctly ucd.

**Comment by yangguanglu** [comment]
@o-u-p

**Comment by o-u-p** [comment]
Please start testing at windows_tony branch @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved.
