### ISSUE TITLE
token lost【bug】

### ISSUE THREAD

**Issue by snake0126** [UCHAIN-WORLD/uchain-fullnode#126]
[root@localhost bin]# ./uc-cli showblock 339988
{
	"hash" : "7e5d276c0c33be0008f0a7144053d6e42fbb2bf003d3c3ad5e252abdd2d1105e",
	"merkle_tree_hash" : "af7f84c6643658a4c96866f15c5dd84701ddfc07ffe5343de4e772a19b1d1689",
	"number" : 339988,
	"previous_block_hash" : "0af36c25a36c1a6cc0161823aecd8e212fbf2ebb0a5379022e079c0b4c1d9576",
	"timestamp" : 1544436647,
	"transaction_count" : 1,
	"transactions" : 
	[
		{
			"hash" : "af7f84c6643658a4c96866f15c5dd84701ddfc07ffe5343de4e772a19b1d1689",
			"inputs" : 
			[
				{
					"address" : "UcuW7wVu198Nuzok8eeMDUNEZQoGqQRRz5",
					"previous_output" : 
					{
						"hash" : "9f0f259dc8ce436cd1068d3d5bbb4d31773ce2b0f2525758e69a169dda19d02e",
						"index" : 0
					},
					"script" : "[ 304402206c65fe734f6fac92c80b425a77610b9491b811b174dc028386e8351bda7327550220490ec0d464a6dc5df59ae51006757f630909d1b41325b812ac6b589bff654fba01 ] [ 02719293264aebc6a987763c89980ef12783491b8dd532fa6db4fe2fc2b23de045 ]",
					"sequence" : 4294967295
				}
			],
			"lock_time" : "0",
			"outputs" : 
			[
				{
					"address" : "UcuW7wVu198Nuzok8eeMDUNEZQoGqQRRz5",
					"asset" : 
					{
						"quantity" : 178,
						"symbol" : "BLOCK",
						"type" : "token-transfer"
					},
					"index" : 0,
					"locked_height_range" : 0,
					"script" : "dup hash160 [ a3af5154c2ee7f294f00e285cdb9489d8cfc8305 ] equalverify checksig",
					"value" : 0
				}
			],
			"version" : "2"
		}
	],
	"version" : 1
}

token lost

**Comment by yangguanglu** [comment]
it is here
Yangs-MacBook-Pro:bin cary$ ./uc-cli showaddresstoken UPZ1nhLVb8zVLewdbRTmbHqZ4hjL2qUon7
[
        {
                "address" : "UPZ1nhLVb8zVLewdbRTmbHqZ4hjL2qUon7",
                "decimal_number" : 1,
                "description" : "BLOCK token is issued by blackhole,just for name not to use",
                "issuer" : "BLACKHOLE",
                "locked_quantity" : 0,
                "quantity" : 113040,
                "secondaryissue_threshold" : 0,
                "status" : "unspent",
                "symbol" : "BLOCK"
        }
]
through this tx
 {
                        "hash" : "a4a4f6351de79aa3b51a582634675023d249152816b9baa017eb308baf33d221",
                        "inputs" :
                        [
                                {
                                        "address" : "UcuW7wVu198Nuzok8eeMDUNEZQoGqQRRz5",
                                        "previous_output" :
                                        {
                                                "hash" : "7b6e150f96d8f5b494a451f8697e409bd9bfca997da4a37e052fe2c773be287e",
                                                "index" : 0
                                        },
                                        "script" : "[ 3044022001f497a4452b9380ecce60dfb6ea90b8266cd456272588b013cee11c2912896c022056c17e7fda8ef12d1fdae8aa51b4a1d7dc8336d89e7023bc65a53563f8a08e6a01 ] [ 02719293264aebc6a987763c89980ef12783491b8dd532fa6db4fe2fc2b23de045 ]",
                                        "sequence" : 4294967295
                                },
                                {
                                        "address" : "UcuW7wVu198Nuzok8eeMDUNEZQoGqQRRz5",
                                        "previous_output" :
                                        {
                                                "hash" : "a8fce8ab2417b56c9b49e09cedae3ced60f584a3596c0591206095b2b02b3b3f",
                                                "index" : 1
                                        },
                                        "script" : "[ 304502210092565e35bac4373badf07b57519eeb8102fb141a4e21915465166f45ca0ea81502201cfde361643aa7d5c825360d608dd64782c3ae2eddc6459e94eb8f616661eba701 ] [ 02719293264aebc6a987763c89980ef12783491b8dd532fa6db4fe2fc2b23de045 ]",
                                        "sequence" : 4294967295
                                }
                        ],
                        "lock_time" : "0",
                        "outputs" :
                        [
                                {
                                        "address" : "UUan4a99WSJHL6UqW9bmfzoYRkaNDeJqsq",
                                        "asset" :
                                        {
                                                "quantity" : 1,
                                                "symbol" : "BLOCK",
                                                "type" : "token-transfer"
                                        },
                                        "index" : 0,
                                        "locked_height_range" : 0,
                                        "script" : "dup hash160 [ 4863b73f0d1c2fc395add3266964831b3a6ab753 ] equalverify checksig",
                                        "value" : 0
                                },
                                {
                                        "address" : "UPZ1nhLVb8zVLewdbRTmbHqZ4hjL2qUon7",
                                        "asset" :
                                        {
                                                "type" : "ucn"
                                        },
                                        "index" : 1,
                                        "locked_height_range" : 0,
                                        "script" : "dup hash160 [ 1135b68c904a1fc0b06e395dbe5529c06d6723f3 ] equalverify checksig",
                                        "value" : 20000
                                },
                                {
                                        "address" : "UPZ1nhLVb8zVLewdbRTmbHqZ4hjL2qUon7",
                                        "asset" :
                                        {
                                                "quantity" : 113040,
                                                "symbol" : "BLOCK",
                                                "type" : "token-transfer"
                                        },
                                        "index" : 2,
                                        "locked_height_range" : 0,
                                        "script" : "dup hash160 [ 1135b68c904a1fc0b06e395dbe5529c06d6723f3 ] equalverify checksig",
                                        "value" : 0
                                }
                        ],
                        "version" : "4"
                }
        ],
        "version" : 1
}
