### ISSUE TITLE
block verified in 0 sec or 0 ms

### ISSUE THREAD

**Issue by Fizzgiggg** [UCHAIN-WORLD/uchain-fullnode#130]
The blocks are being shown as verifying in 0 sec and 0 ms. 

20181212T132652 INFO [blockchain] Block [428349] verify (1) txs and (1) inputs
20181212T132652 INFO [blockchain] Block [428349] verified in (0) secs or (0) ms/input
20181212T132653 INFO [blockchain] Block [428350] verify (1) txs and (1) inputs
20181212T132653 INFO [blockchain] Block [428350] verified in (0) secs or (0) ms/input
20181212T132653 INFO [blockchain] Block [428351] verify (1) txs and (1) inputs
20181212T132653 INFO [blockchain] Block [428351] verified in (0) secs or (0) ms/input
20181212T132654 INFO [blockchain] Block [428352] verify (1) txs and (1) inputs
20181212T132654 INFO [blockchain] Block [428352] verified in (0) secs or (0) ms/input

**Comment by yuyuyu2018** [comment]
说明cpu不错，没有耗费多少时间在运算上
