### ISSUE TITLE
Wallet balance is the same after casting a vote of 5【bug】

### ISSUE THREAD

**Issue by TahiG-zz** [UCHAIN-WORLD/uchain-fullnode#133]
![screen shot 2018-12-11 at 03 47 12](https://user-images.githubusercontent.com/22755405/49893714-ff0b6180-fe43-11e8-9983-df556731f74d.png)

Wallet balance 44959660 before casting a vote of 5 and 44959660 after.

**Comment by yuyuyu2018** [comment]
please wait for minute,then see

**Comment by TahiG** [comment]
Is that the official block time? 60 seconds?

**Comment by yuyuyu2018** [comment]
maybe，it hasn't entered the memory pool yet
