### ISSUE TITLE
changepass --password positional【bug】

### ISSUE THREAD

**Issue by UmckaBear** [UCHAIN-WORLD/uchain-fullnode#135]
Wiki description:
**changepass**
Parameters (optional)
_-p or [--password] New password/authorization._

Running **changepass** command without [**-p**] gives response:

```
E:\Uchain\UChain_UIP0.2.windows\bin>uc-cli.exe changepass UmckaTest1 2gether
{
        "code" : 1021,
        "message" : "the option '--password' is required but missing"
 }
```

**Comment by yuyuyu2018** [comment]
wiki have been  modified
