### ISSUE TITLE
Possibility delete addresses from account (using addaddress command)【 requirement】

### ISSUE THREAD

**Issue by UmckaBear** [UCHAIN-WORLD/uchain-fullnode#136]
There is no possibility remove addresses from account. User can only fully remove account.
As example, user used **addaddress** command with **-n** parameter. There no limitation for -n parameter (10 or 100) and user tried create 100000 addresses

E:\Uchain\UChain_UIP0.2.windows\bin>uc-cli.exe addaddress -n 100000 UmckaTest1 2gether

He started command but change immediately decision (wrong account) and terminated command using ctrl+C, for example in Windows. There were already created additional addresses. So he need remove new addresses.

**Comment by o-u-p** [comment]
Please start testing at UIP0.5_tony branch @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved.
