### ISSUE TITLE
Commands can also be executed with nonexistent usernames and passwords【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#141]
D:\>uc-cli showinfo  ceshiceshi 123
{
        "database_version" : "0.0.2",
        "height" : 457926,
        "is_mining" : false,
        "miner-count" : 3,
        "peers" : 8,
        "protocol_version" : 70012,
        "testnet" : false,
        "token_count" : 2,
        "wallet_account_count" : 9,
        "wallet_version" : "0.0.2"
}
shutdown、showpeers、addpeer

**Comment by o-u-p** [comment]
These functions should be controlled by the administrator, the feature hasn't been complete yet.

**Comment by yuyuyu2018** [comment]
The function is not perfect yet, close first
