### ISSUE TITLE
issues and suggestions on git page.

### ISSUE THREAD

**Issue by cryptonull** [UCHAIN-WORLD/uchain-fullnode#158]
as I write on telegram:
some istructions on git are not correct (cloning a git by copy paste does not work because you have a old adress)
I suggest to put the part of needed dependencies before the the BUILD  UC ... so first 

ZeroMQ 4.2.5+ modules
secp256k1 modules
boost 1.60 reccomended
miniupnpc if needed

then 
build UC

there is an error on the build UC git:
 git clone https://github.com/UCHAIN-WORLD/UChain.git  <— wrong address for a git
 git clone https://github.com/UCHAIN-WORLD/uchain-fullnode.git correct one
 then
cd uchain-fullnode  && mkdir build && cd build
then 

make -j4 (-j4 is not always the rigth parameter... could be j2 or j8 it depends by the cpu)

and I suggest to modify: 
   make install 
in
   make install-strip --> it strips

also you need to made a:

chmod +x ./install_thirdlibrary 
before do
sudo ./install_thirdlibrary --build-boost --build-upnpc

**Comment by cryptonull** [comment]
as I write on Telegram:

**Comment by yangguanglu** [comment]
thanks,that is very useful and helpful!

**Comment by yangguanglu** [comment]
It is modified.You can reopen it when it is still not right.
