### ISSUE TITLE
some api call's response is not standard[bug]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#159]
for example:
Yangs-MacBook-Pro:bin cary$ ./uc-cli addpeer 192.168.16.102:5682
success
there need to be a json object.

**Comment by yangguanglu** [comment]
@o-u-p check all the api calls to find these problem and fix.

**Comment by o-u-p** [comment]
It should be fixed, please check it @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
[tony@localhost bin]$ ./uc-cli addpeer 192.168.16.128:5682
success
[tony@localhost bin]$ ./uc-cli showpeers
[
	"116.62.238.230:5682",
	"112.74.181.29:5682",
	"13.124.250.27:5682",
	"120.78.209.248:5682",
	"192.168.16.169:33898",
	"192.168.16.169:5682"
]

**Comment by o-u-p** [comment]
Wait for a while @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
no problem
