### ISSUE TITLE
api doc error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#161]
body
  { 
        "jsonrpc": "3.0",  
        "method":"showblockheight",
         "id": 7   
      }

Response：
{
	"id" : 7,
	"jsonrpc" : "2.0",
	"result" : 695242
}

request  "jsonrpc": "3.0" ；   Response： "jsonrpc" : "2.0",

**Comment by o-u-p** [comment]
It should be fixed @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved.
