### ISSUE TITLE
-f parameter description of the problem【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#175]
[tony@localhost bin]$ ./uc-cli registeruid -h

Usage: uc-cli registeruid [-h] [--fee value] [--percentage value]        
ACCOUNTNAME ACCOUNTAUTH ADDRESS SYMBOL                                   

Info: registeruid                                                        

Options (named):

-h [--help]          Get a description and instructions for this command.
-f [--fee]           The fee of tx. defaults to 100 ucn.                 
-p [--percentage]    Percentage of fee send to miner. minimum is 20.     

ucn change to UCN

**Comment by o-u-p** [comment]
It should  be fine in  UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved.
