### ISSUE TITLE
transferuid command cannot be executed 【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#180]
[tony@localhost bin]$ ./uc-cli transferuid yujiali18 123456 Ujp2ym6t6LrCYUWaTPhFXVmtiea7wR6NJy 130126194@qq.com
{
	"code" : 3302,
	"message" : "not enough balance, unspent = 0, payment = 200000"
}

[tony@localhost bin]$ ./uc-cli showbalances yujiali18 123456
[
	{
		"address" : "Ujp2ym6t6LrCYUWaTPhFXVmtiea7wR6NJy",
		"available" : 0,
		"confirmed" : 0,
		"frozen" : 0,
		"received" : 0,
		"unspent" : 0
	},
	{
		"address" : "UWeDQ4Bfc9zfv8KutkCbXdHKmL14VTAwnT",
		"available" : 20000000000,
		"confirmed" : 20000000000,
		"frozen" : 0,
		"received" : 50000000000,
		"unspent" : 20000000000
	},
	{
		"address" : "UNWQUK39TFrQD8GZi7QJ1iwBaTToNkbXrt",
		"available" : 20000000000,
		"confirmed" : 20000000000,
		"frozen" : 0,
		"received" : 50000000000,
		"unspent" : 20000000000
	},
	{
		"address" : "UP3aApWUEeYGUPuv7aQfRnSfD9Z9rYw1wp",
		"available" : 20000000000,
		"confirmed" : 20000000000,
		"frozen" : 0,
		"received" : 50000000000,
		"unspent" : 20000000000
	},
	{
		"address" : "UNoorqx4SrtRUUNsVKMyrLDHKWFoovQ5dA",
		"available" : 30000000000,
		"confirmed" : 30000000000,
		"frozen" : 0,
		"received" : 50000000000,
		"unspent" : 30000000000
	},
	{
		"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
		"available" : 10000000000,
		"confirmed" : 10000000000,
		"frozen" : 0,
		"received" : 30000000000,
		"unspent" : 10000000000
	}
]
only the Ujp2ym6t6LrCYUWaTPhFXVmtiea7wR6NJy have no ucn

**Comment by o-u-p** [comment]
It is exactly the rule @yuyuyu2018  .
