### ISSUE TITLE
transfercandidate command execution failed【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#184]
[tony@localhost bin]$ ./uc-cli showuids yujiali18 123456
{
	"current_page" : 1,
	"total_count" : 4,
	"total_page" : 1,
	"uids" : 
	[
		{
			"address" : "Ujp2ym6t6LrCYUWaTPhFXVmtiea7wR6NJy",
			"status" : "registered",
			"symbol" : "130126194@qq.com"
		},
		{
			"address" : "UP3aApWUEeYGUPuv7aQfRnSfD9Z9rYw1wp",
			"status" : "registered",
			"symbol" : "1301261@qq.com"
		},
		{
			"address" : "UNWQUK39TFrQD8GZi7QJ1iwBaTToNkbXrt",
			"status" : "registered",
			"symbol" : "130126@qq.com"
		},
		{
			"address" : "UWeDQ4Bfc9zfv8KutkCbXdHKmL14VTAwnT",
			"status" : "registered",
			"symbol" : "13012@qq.com"
		}
	]
}

[tony@localhost bin]$ ./uc-cli transfercandidate  yujiali18 123456 130126@qq.com 192.168.16.169:22
{
	"code" : 5304,
	"message" : "validate transaction failure"
}
[tony@localhost bin]$ ./uc-cli showcandidates yujiali18 123456
[
	{
		"address" : "UP3aApWUEeYGUPuv7aQfRnSfD9Z9rYw1wp",
		"content" : "",
		"status" : "registered",
		"symbol" : "192.168.16.169:22"
	},

**Comment by o-u-p** [comment]
Please start testing at UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved.
