### ISSUE TITLE
 vote token can not be destroyed 【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#188]
[tony@localhost bin]$ ./uc-cli showtokens yujiali18 123456
[
	{
		"decimal_number" : 1,
		"description" : "'VOTE' token is issued by blackhole.Users can use it to vote.",
		"issuer" : "BLACKHOLE",
		"locked_quantity" : 0,
		"quantity" : 1,
		"secondaryissue_threshold" : 0,
		"status" : "unspent",
		"symbol" : "VOTE"
	}
]

[tony@localhost bin]$ ./uc-cli showuids yujiali18 123456
{
	"current_page" : 1,
	"total_count" : 1,
	"total_page" : 1,
	"uids" : 
	[
		{
			"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
			"status" : "registered",
			"symbol" : "1487980518@qq.COM"
		}
	]
}

[tony@localhost bin]$ ./uc-cli vote -r BLACKHOLE:1 yujiali18 123456 1487980518@qq.COM 
{
	"code" : 4012,
	"message" : "not supported version target address 1111111111111111111114oLvT2"
}

**Comment by o-u-p** [comment]
Please start testing at UIP0.5_tony branch @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
tony@ubuntu:~/project/uchain-fullnode/build/bin$ ./uc-cli showaddresstoken  UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9
[
	{
		"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
		"decimal_number" : 0,
		"description" : "",
		"issuer" : "1487980518@qq.COM",
		"locked_quantity" : 0,
		"quantity" : 100,
		"secondaryissue_threshold" : 0,
		"status" : "unspent",
		"symbol" : "BALALA"
	},
	{
		"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
		"decimal_number" : 1,
		"description" : "'VOTE' token is issued by blackhole.Users can use it to vote.",
		"issuer" : "BLACKHOLE",
		"locked_quantity" : 0,
		"quantity" : 1,
		"secondaryissue_threshold" : 0,
		"status" : "unspent",
		"symbol" : "VOTE"
	},
	{
		"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
		"decimal_number" : 0,
		"description" : "",
		"issuer" : "1487980518@qq.COM",
		"locked_quantity" : 0,
		"quantity" : 100,
		"secondaryissue_threshold" : 0,
		"status" : "unspent",
		"symbol" : "YU."
	}
]
tony@ubuntu:~/project/uchain-fullnode/build/bin$  ./uc-cli vote -r BLACKHOLE:1 yujiali18 123456 1487980518@qq.COM
{
	"hash" : "89a8fffc23d65db6a7cc14f641dd285873dfc1babbf0b1668530e0491957a396",
	"inputs" : 
	[
		{
			"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
			"previous_output" : 
			{
				"hash" : "944055c269c7c7bb5e8650fd4ab05b592c6299356cb6c0bbf193d3fe79affbb4",
				"index" : 0
			},
			"script" : "[ 304402200dada87e6ffecf4f4239921916300356951568956e2d0c9b1da48388ee2f2f2602206ff1ebcf3aa83be99dd3cebdafdc89ea8714843aa2ddd9ae914a98ddf48d12a101 ] [ 0351e675bb51a1f20251559353076ae259b2c969ef030488b4c9379b6962a35127 ]",
			"sequence" : 4294967295
		}
	],
	"lock_time" : "0",
	"outputs" : 
	[
		{
			"address" : "1111111111111111111114oLvT2",
			"asset" : 
			{
				"from_uid" : "1487980518@qq.COM",
				"quantity" : 1,
				"symbol" : "VOTE",
				"to_uid" : "BLACKHOLE",
				"type" : "token-transfer"
			},
			"index" : 0,
			"locked_height_range" : 0,
			"script" : "return",
			"value" : 0
		},
		{
			"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
			"asset" : 
			{
				"to_uid" : "1487980518@qq.COM",
				"type" : "ucn"
			},
			"index" : 1,
			"locked_height_range" : 345600,
			"script" : "[ 004605 ] numequalverify dup hash160 [ d6be18ad169d9ec60871f92b4571c6fca0f0ab8f ] equalverify checksig",
			"value" : 5000000
		},
		{
			"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
			"asset" : 
			{
				"type" : "ucn"
			},
			"index" : 2,
			"locked_height_range" : 0,
			"script" : "dup hash160 [ d6be18ad169d9ec60871f92b4571c6fca0f0ab8f ] equalverify checksig",
			"value" : 299994800000
		}
	],
	"version" : "4"
}


tony@ubuntu:~/project/uchain-fullnode/build/bin$ ./uc-cli showtx 89a8fffc23d65db6a7cc14f641dd285873dfc1babbf0b1668530e0491957a396
{
	"hash" : "89a8fffc23d65db6a7cc14f641dd285873dfc1babbf0b1668530e0491957a396",
	"height" : 311660,
	"inputs" : 
	[
		{
			"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
			"previous_output" : 
			{
				"hash" : "944055c269c7c7bb5e8650fd4ab05b592c6299356cb6c0bbf193d3fe79affbb4",
				"index" : 0
			},
			"script" : "[ 304402200dada87e6ffecf4f4239921916300356951568956e2d0c9b1da48388ee2f2f2602206ff1ebcf3aa83be99dd3cebdafdc89ea8714843aa2ddd9ae914a98ddf48d12a101 ] [ 0351e675bb51a1f20251559353076ae259b2c969ef030488b4c9379b6962a35127 ]",
			"sequence" : 4294967295
		}
	],
	"lock_time" : "0",
	"outputs" : 
	[
		{
			"address" : "1111111111111111111114oLvT2",
			"asset" : 
			{
				"from_uid" : "1487980518@qq.COM",
				"quantity" : 1,
				"symbol" : "VOTE",
				"to_uid" : "BLACKHOLE",
				"type" : "token-transfer"
			},
			"index" : 0,
			"locked_height_range" : 0,
			"script" : "return",
			"value" : 0
		},
		{
			"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
			"asset" : 
			{
				"to_uid" : "1487980518@qq.COM",
				"type" : "ucn"
			},
			"index" : 1,
			"locked_height_range" : 345600,
			"script" : "[ 004605 ] numequalverify dup hash160 [ d6be18ad169d9ec60871f92b4571c6fca0f0ab8f ] equalverify checksig",
			"value" : 5000000
		},
		{
			"address" : "UhZUHZjrfBvWLz3ikuwspGmt8nBxH822q9",
			"asset" : 
			{
				"type" : "ucn"
			},
			"index" : 2,
			"locked_height_range" : 0,
			"script" : "dup hash160 [ d6be18ad169d9ec60871f92b4571c6fca0f0ab8f ] equalverify checksig",
			"value" : 299994800000
		}
	],
	"version" : "4"
}

**Comment by yuyuyu2018** [comment]
After verification still have

**Comment by yuyuyu2018** [comment]
This is the logic
