### ISSUE TITLE
The transaction fee is not correct 【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#189]
[tony@localhost bin]$ ./uc-cli sendto -h

Usage: uc-cli sendto [-h] [--change value] [--fee value] [--memo value]  
ACCOUNTNAME ACCOUNTAUTH TO_ AMOUNT                                       

Info: send ucn to a targert uid/address.                                 

Options (named):

-h [--help]          Get a description and instructions for this command.
-c [--change]        Change to this uid/address,should be yours.         
-f [--fee]           Transaction fee. defaults to 10000 UCN.             
-m [--memo]          Attached memo for this transaction.                 

Arguments (positional):

ACCOUNTNAME          Account name required.                              
ACCOUNTAUTH          Account password(authorization) required.           
TO_                  Send to this uid/address                            
AMOUNT               UCN integer bits.  

sendfrom ， sendtomulti， sendfrom，createrawtx，createmultisigtx 
These are problems

**Comment by yuyuyu2018** [comment]
The registertoken command transaction fee is not correct

**Comment by o-u-p** [comment]
Start test in master @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
The registertoken command transaction fee is not correct @o-u-p

**Comment by yuyuyu2018** [comment]
no problem
