### ISSUE TITLE
The transaction fee bound fixed address 【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#196]
[root@localhost bin]# ./uc-cli showbalances yujiali3 123456
[
	{
		"address" : "UVjsbgzEQZqqN3sM3MXrHwjvQ1MQggiXf9",
		"available" : 50000000000000,
		"confirmed" : 50000000000000,
		"frozen" : 0,
		"received" : 50000000400000,
		"unspent" : 50000000000000
	},
	{
		"address" : "3F81QMhhtBp4cK4WmDvYxRPVVfbEeZSV93",
		"available" : 1990000000000,
		"confirmed" : 1990000000000,
		"frozen" : 0,
		"received" : 3990000000000,
		"unspent" : 1990000000000
	},
	{
		"address" : "Ub9Utbs3hHMharWZBenvU8TjbygAXNtD5L",
		"available" : 9989994900000,
		"confirmed" : 9989999900000,
		"frozen" : 5000000,
		"received" : 75969994700000,
		"unspent" : 9989999900000
	}
]
[root@localhost bin]# ./uc-cli  registercandidate  -c 注册候选人 yujiali3 123456 1301261946@qq.com 192.168.16.169:22
{
	"code" : 3302,
	"message" : "not enough balance, unspent = 50000000000000, payment = 50010000000000"
}

**Comment by o-u-p** [comment]
It should be correct rule.

**Comment by yuyuyu2018** [comment]
no problem
