### ISSUE TITLE
Enter 5 characters to change password, you can succeed【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#206]
./uc-cli changepass -p 12345 yujiali3 123456;
{
	"name" : "yujiali3",
	"status" : "changed successfully"
}
tony@ubuntu:~/project/uchain-fullnode/build/bin$ ./uc-cli showbalance yujiali3 12345
{
	"total_available" : 20997996500000,
	"total_confirmed" : 70998001500000,
	"total_frozen" : 50000005000000,
	"total_received" : 245967996700000,
	"total_unspent" : 70998001500000
}

**Comment by o-u-p** [comment]
It should not be a problem.

**Comment by yuyuyu2018** [comment]
no problem
