### ISSUE TITLE
registercandidate need to check if this address registered candidate[reqqurement]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#214]
if regitstered ,forbide to register

**Comment by o-u-p** [comment]
Fixed at UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
There's still a problem
@o-u-p

**Comment by yuyuyu2018** [comment]
[tony@localhost bin]$ ./uc-cli showcandidates 
[
	{
		"address" : "UTKj2s8sx6SkQuniK61SuxsWu9DypQwfbZ",
		"content" : "",
		"height" : 126052,
		"status" : "registered",
		"symbol" : "houxuanren2@qq.com",
		"timestamp" : 1545977025,
		"to_uid" : "20181228@qq.com"
	},
	{
		"address" : "UTKj2s8sx6SkQuniK61SuxsWu9DypQwfbZ",
		"content" : "",
		"height" : 121099,
		"status" : "registered",
		"symbol" : "houxuanren@qq.com",
		"timestamp" : 1545968162,
		"to_uid" : "20181228@qq.com"
	},

**Comment by yuyuyu2018** [comment]
have been fixed
