### ISSUE TITLE
addpeer command can not add node address【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#217]
[root@localhost bin]# ./uc-cli addpeer 192.168.16.147:5682
{
	"code" : 1000,
	"message" : "the argument for option is invalid"
}

**Comment by o-u-p** [comment]
It should be fixed, please start testing at UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
have been fixed
