### ISSUE TITLE
vote command can not into the memory pool【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#230]
[tony@localhost bin]$ ./uc-cli vote -r reward_pool:20 yujiali3 123456 1301261946@qq.com
{
	"hash" : "f04753c58949093a6b96913e91ca903ca899c5fc35829ad0aa4bda9b5ea35d12",
	"inputs" : 
	[
		{
			"address" : "UVjsbgzEQZqqN3sM3MXrHwjvQ1MQggiXf9",
			"previous_output" : 
			{
				"hash" : "d05bc6a4a8147143ad9be4151770cae07518f23b7bc7a846158698380dfdc76e",
				"index" : 2
			},
			"script" : "[ 304402206f75403eef690438e485400190915872e0893806dca23f110460a831ac8f8c3c02204bd012c1f71f21d7b54e511307e757da5b3dc6dc4c3c5a1cb17d3d7ec87c5e3c01 ] [ 026abc6d06808ebd752355a27848d5d9686eb21711225ccd090c3cd565dabb5e60 ]",
			"sequence" : 4294967295
		}
	],
	"lock_time" : "0",
	"outputs" : 
	[
		{
			"address" : "UkwAarnHiVUoBi4mHupZ3GyLcVLDxPe9eo",
			"asset" : 
			{
				"from_uid" : "1301261946@qq.com",
				"quantity" : 20,
				"symbol" : "VOTE",
				"to_uid" : "reward_pool",
				"type" : "token-transfer"
			},
			"index" : 0,
			"locked_height_range" : 0,
			"script" : "dup hash160 [ fbc0d920de99eb7d9d2c56d9b216253b4a4d3eb0 ] equalverify checksig",
			"value" : 0
		},
		{
			"address" : "UVjsbgzEQZqqN3sM3MXrHwjvQ1MQggiXf9",
			"asset" : 
			{
				"to_uid" : "1301261946@qq.com",
				"type" : "ucn"
			},
			"index" : 1,
			"locked_height_range" : 345600,
			"script" : "[ 004605 ] numequalverify dup hash160 [ 551434f746a34cc34c80653cb4938b9f9a3b1cc2 ] equalverify checksig",
			"value" : 100000000
		},
		{
			"address" : "UVjsbgzEQZqqN3sM3MXrHwjvQ1MQggiXf9",
			"asset" : 
			{
				"type" : "ucn"
			},
			"index" : 2,
			"locked_height_range" : 0,
			"script" : "dup hash160 [ 551434f746a34cc34c80653cb4938b9f9a3b1cc2 ] equalverify checksig",
			"value" : 9989894890000
		}
	],
	"version" : "4"
}
[tony@localhost bin]$ ./uc-cli showtx f04753c58949093a6b96913e91ca903ca899c5fc35829ad0aa4bda9b5ea35d12
{
	"code" : 5306,
	"message" : "transaction does not exist!"
}

**Comment by o-u-p** [comment]
The UID reward_pool is not registered.

**Comment by yuyuyu2018** [comment]
Close first
