### ISSUE TITLE
showblockheaders command execution failure【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#238]
[tony@localhost bin]$ ./uc-cli showblockheaders -e 10000:115222
{
	"code" : 5103,
	"message" : "Cannot get block headers much than 10000!"
}

**Comment by yuyuyu2018** [comment]
![qq 20181228105050](https://user-images.githubusercontent.com/45030364/50500784-7836c580-0a8e-11e9-8e90-caa8bf7d1378.png)
）change to ]

**Comment by o-u-p** [comment]
Fixed at UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
tony@ubuntu:~/project/uchain-fullnode/build/bin$ ./uc-cli showblockheaders
{
	"code" : 1021,
	"message" : "null\n"
}
tony@ubuntu:~/project/uchain-fullnode/build/bin$ ./uc-cli showblockheaders  -e 0:1
{
	"code" : 1021,
	"message" : "null\n"
}
@o-u-p

**Comment by o-u-p** [comment]
It should be fixed in UIP0.5_tony .

**Comment by o-u-p** [comment]
fixed UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved.
