### ISSUE TITLE
showtxs command prompt error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#239]
[tony@localhost bin]$ ./uc-cli showtxs
{
	"code" : 2003,
	"message" : "no record in this page"
}

I have a tx

**Comment by yuyuyu2018** [comment]
![qq 20181228105927](https://user-images.githubusercontent.com/45030364/50500969-aa94f280-0a8f-11e9-8281-22881cf32a84.png)

**Comment by o-u-p** [comment]
Fixed at UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
have been fixed
