### ISSUE TITLE
when ucd is running【bug】

### ISSUE THREAD

**Issue by snake0126** [UCHAIN-WORLD/uchain-fullnode#240]
![f6ab3ca3f91723bbfeeb52324d35f59](https://user-images.githubusercontent.com/6120407/50501105-9ac9de00-0a90-11e9-94d5-4dff3287bc1c.png)

in error.log

**Comment by o-u-p** [comment]
Please show how to reproduce it @snake0126  .

**Comment by o-u-p** [comment]
Since it cannot be reproduced, close it temporarily @yuyuyu2018  .
