### ISSUE TITLE
Websocket server can not start【bug】

### ISSUE THREAD

**Issue by snake0126** [UCHAIN-WORLD/uchain-fullnode#242]
![05e6c47a0a88ae800b0a8b400d40dca](https://user-images.githubusercontent.com/6120407/50501114-b8974300-0a90-11e9-8be2-bda1ce526536.png)
error log  display  Websocket server can not start with ucd dead

**Comment by o-u-p** [comment]
Refer to the description, it only happens when restart ucd, I can reproduce it when the port is in use, if you can reproduce it, please let me know, so close it temporarily @yuyuyu2018  .
