### ISSUE TITLE
showvote command  didn't work.【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#243]
[tony@localhost bin]$ ./uc-cli showtx a1ebf8a3bec561194dae44a6d837a10ef427a8017204b748e0f70e944611df92
{
	"hash" : "a1ebf8a3bec561194dae44a6d837a10ef427a8017204b748e0f70e944611df92",
	"height" : 123420,
	"inputs" : 

[tony@localhost bin]$ ./uc-cli showvote   2018122@qq.com 1 123420
[
	{
		"address" : "UTuHqxH7PectCZhG3NSFATLXVqGYpTt8Wt",
		"decimal_number" : 1,
		"description" : "'VOTE' token is issued by blackhole.Users can use it to vote.",
		"issuer" : "BLACKHOLE",
		"locked_quantity" : 0,
		"quantity" : 20,
		"secondaryissue_threshold" : 0,
		"status" : "unspent",
		"symbol" : "VOTE"
	}
]
[tony@localhost bin]$ ./uc-cli showvote  2018122@qq.com 1 1234
[
	{
		"address" : "UTuHqxH7PectCZhG3NSFATLXVqGYpTt8Wt",
		"decimal_number" : 1,
		"description" : "'VOTE' token is issued by blackhole.Users can use it to vote.",
		"issuer" : "BLACKHOLE",
		"locked_quantity" : 0,
		"quantity" : 20,
		"secondaryissue_threshold" : 0,
		"status" : "unspent",
		"symbol" : "VOTE"
	}
]

**Comment by o-u-p** [comment]
fixed at UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved.
