### ISSUE TITLE
vote coinbase is useless ,value =0 and has nothing else[bug]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#25]
./uc-cli showblock 22401
{
        "bits" : "10",
        "hash" : "1228b7a50f071831d583fa747c1439005fb3f64dea4b4a0e9b295640a29af2b7",
        "merkle_tree_hash" : "57e374d8bc51acf5ce6978540f1f0aac71421841f655152b298737a5121c2ee0",
        "mixhash" : "56667354250779342226461823063581821423947739516576578976349897385486089995912",
        "nonce" : "15277487032237240731",
        "number" : 22401,
        "previous_block_hash" : "3c836cf7ce5ec37835ab4f55fdaf28c993aa4af4081aa4036bed08e39d653689",
        "timestamp" : 1541055954,
        "transaction_count" : 3,
        "transactions" :
        [
                {
                        "hash" : "e57b1c20ad246d0dae962246fcf63484fe2f5949963eca56928fd423c8026bf8",
                        "inputs" :
                        [
                                {
                                        "previous_output" :
                                        {
                                                "hash" : "0000000000000000000000000000000000000000000000000000000000000000",
                                                "index" : 4294967295
                                        },
                                        "script" : "[ 028157 ]",
                                        "sequence" : 0
                                }
                        ],
                        "lock_time" : "0",
                        "outputs" :
                        [
                                {
                                        "address" : "UkRYvsnfJkwSTAUCcZnqCK8sE1ZYJP6so7",
                                        "asset" :
                                        {
                                                "type" : "ucn"
                                        },
                                        "index" : 0,
                                        "locked_height_range" : 0,
                                        "script" : "dup hash160 [ f62705a6cfc44ad47792988464b6e47a06ef114a ] equalverify checksig",
                                        "value" : 20000
                                },
                                {
                                        "address" : "UkRYvsnfJkwSTAUCcZnqCK8sE1ZYJP6so7",
                                        "asset" :
                                        {
                                                "quantity" : 1,
                                                "symbol" : "BLOCK",
                                                "type" : "token-transfer"
                                        },
                                        "index" : 1,
                                        "locked_height_range" : 0,
                                        "script" : "dup hash160 [ f62705a6cfc44ad47792988464b6e47a06ef114a ] equalverify checksig",
                                        "value" : 0
                                }
                        ],
                        "version" : "1"
                },
                {
                        "hash" : "b0d30da1b127951511c991364e33cb94911af4904b79581a824965e87ae6099a",
                        "inputs" :
                        [
                                {
                                        "previous_output" :
                                        {
                                                "hash" : "0000000000000000000000000000000000000000000000000000000000000000",
                                                "index" : 4294967295
                                        },
                                        "script" : "[ 028157 ]",
                                        "sequence" : 0
                                }
                        ],
                        "lock_time" : "22399",
                        "outputs" :
                        [
                                {
                                        "address" : "UNfrtAxhJRi83PjTPjV3yNPKnjLYR22Bhx",
                                        "asset" :
                                        {
                                                "type" : "ucn"
                                        },
                                        "index" : 0,
                                        "locked_height_range" : 345600,
                                        "script" : "[ 004605 ] numequalverify dup hash160 [ 078910a58cea508623e2be9b38beb6e7d576e880 ] equalverify checksig",
                                        "value" : 0
                                },
                                {
                                        "address" : "UNfrtAxhJRi83PjTPjV3yNPKnjLYR22Bhx",
                                        "asset" :
                                        {
                                                "quantity" : 1,
                                                "symbol" : "BLOCK",
                                                "type" : "token-transfer"
                                        },
                                        "index" : 1,
                                        "locked_height_range" : 345600,
                                        "script" : "[ 004605 ] numequalverify dup hash160 [ 078910a58cea508623e2be9b38beb6e7d576e880 ] equalverify checksig",
                                        "value" : 0
                                }
                        ],
                        "version" : "1"
                },
                {
                        "hash" : "b3357421af0434c4d3d8e42433903d8f653803f3d2418d942ea0bed2e1da6384",
                        "inputs" :
                        [
                                {
                                        "address" : "UkRYvsnfJkwSTAUCcZnqCK8sE1ZYJP6so7",
                                        "previous_output" :
                                        {
                                                "hash" : "3209d93bc7f20364952aedaac876eb2001508f33a4a2145039e982c830c33fb1",
                                                "index" : 0
                                        },
                                        "script" : "[ 3045022100c9a6e25655e9eb0202351e05e048b59b62672d00de1ee96e2984258d0be83a17022078df40602dbcfe9bfcb9100d6ff9529a8830662ed0f28854dd7b7e3fc16ed66801 ] [ 0386e78227d2e2a80e5d99a727a48b67501ea87223634544a38ae1c1720e59167d ]",
                                        "sequence" : 4294967295
                                },
                                {
                                        "address" : "UkRYvsnfJkwSTAUCcZnqCK8sE1ZYJP6so7",
                                        "previous_output" :
                                        {
                                                "hash" : "2da6f0b77b6367d11f9c84b81213a6e5dbf830211f23bbde367babdf7d82f369",
                                                "index" : 0
                                        },
                                        "script" : "[ 304402201bd11ce945ea2b01402f687d466fb5ddc303e5959d9ff320f4ef73601ee6b567022055ab453f6a59af1abca2e9fd0d3bf8e5754471741d8807924a998d84d0b658db01 ] [ 0386e78227d2e2a80e5d99a727a48b67501ea87223634544a38ae1c1720e59167d ]",
                                        "sequence" : 4294967295
                                }
                        ],
                        "lock_time" : "0",
                        "outputs" :
                        [
                                {
                                        "address" : "UNfrtAxhJRi83PjTPjV3yNPKnjLYR22Bhx",
                                        "asset" :
                                        {
                                                "type" : "ucn"
                                        },
                                        "index" : 0,
                                        "locked_height_range" : 345600,
                                        "script" : "[ 004605 ] numequalverify dup hash160 [ 078910a58cea508623e2be9b38beb6e7d576e880 ] equalverify checksig",
                                        "value" : 5000
                                },
                                {
                                        "address" : "Ughe1bqD5xbrBzDX4mH5t1r9cueZqu8c5x",
                                        "asset" :
                                        {
                                                "quantity" : 1,
                                                "symbol" : "VOTE",
                                                "type" : "token-transfer"
                                        },
                                        "index" : 1,
                                        "locked_height_range" : 0,
                                        "script" : "dup hash160 [ cd516a86ff6fa4d13ce004705c447fd363210b51 ] equalverify checksig",
                                        "value" : 0
                                },
                                {
                                        "address" : "UkRYvsnfJkwSTAUCcZnqCK8sE1ZYJP6so7",
                                        "asset" :
                                        {
                                                "type" : "ucn"
                                        },
                                        "index" : 2,
                                        "locked_height_range" : 0,
                                        "script" : "dup hash160 [ f62705a6cfc44ad47792988464b6e47a06ef114a ] equalverify checksig",
                                        "value" : 5000
                                }
                        ],
                        "version" : "4"
                }
        ],
        "version" : 1
}

**Comment by yangguanglu** [comment]
@o-u-p

**Comment by yangguanglu** [comment]
and 2 block coinbase ,it is wrong

**Comment by o-u-p** [comment]
This should be a config error of miner address.

**Comment by yangguanglu** [comment]
fixed @yuyuyu2018
