### ISSUE TITLE
showminers dose not show the candidates's vote after voted[bug]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#269]
Yangs-MacBook-Pro:bin cary$ ./uc-cli vote yang 123456 yang -r ceshixia2@qq.com:500
{
        "hash" : "2c09ae745211c99b1e92e44630a5c3fd5248e93604410cec59391b23e4dfff9a",
        "inputs" :
        [
                {
                        "address" : "UYAapFPXtdi3W87fFkcgDEUuE5QGJSNEcN",
                        "previous_output" :
                        {
                                "hash" : "49ccfa2dd34e161a17512b08bd860ace0b397ec1a83dd4a2eb2bb7ac2aea2459",
                                "index" : 2
                        },
                        "script" : "[ 3045022100c1f75eca47ad1ae4bec61f0d3ba488a5b55c436120eea09f13a779e8ac30d9b10220663f4a590be74e0e2deda6c28725c7ea2a4bb792136cdaecb5db30aef208f8fa01 ] [ 03451305d72229a1a25b4a3f1fff37589903fc3d4163be4cef9383873986a86e40 ]",
                        "sequence" : 4294967295
                }
        ],
        "lock_time" : "0",
        "outputs" :
        [
                {
                        "address" : "UNR6s87LD9TsG2XrRVFSpWz1yPpv5oN43V",
                        "asset" :
                        {
                                "from_uid" : "yang",
                                "quantity" : 500,
                                "symbol" : "VOTE",
                                "to_uid" : "ceshixia2@qq.com",
                                "type" : "token-transfer"
                        },
                        "index" : 0,
                        "locked_height_range" : 0,
                        "script" : "dup hash160 [ 04be7f42a857d2722cc74603a7170be306945fb8 ] equalverify checksig",
                        "value" : 0
                },
                {
                        "address" : "UYAapFPXtdi3W87fFkcgDEUuE5QGJSNEcN",
                        "asset" :
                        {
                                "to_uid" : "yang",
                                "type" : "ucn"
                        },
                        "index" : 1,
                        "locked_height_range" : 345600,
                        "script" : "[ 004605 ] numequalverify dup hash160 [ 6fb0d8ed7f5d6165a9c175322c9c0262b28816a9 ] equalverify checksig",
                        "value" : 2500000000
                },
                {
                        "address" : "UYAapFPXtdi3W87fFkcgDEUuE5QGJSNEcN",
                        "asset" :
                        {
                                "type" : "ucn"
                        },
                        "index" : 2,
                        "locked_height_range" : 0,
                        "script" : "dup hash160 [ 6fb0d8ed7f5d6165a9c175322c9c0262b28816a9 ] equalverify checksig",
                        "value" : 87499800000
                }
        ],
        "version" : "4"
}
Yangs-MacBook-Pro:bin cary$ ./uc-cli showminers
[
        {
                "address" : "UXSWuBvP9MtXU8NfZZPjeYEkn71mgUBXVm",
                "content" : "矿工1",
                "height" : 2929,
                "status" : "registered",
                "symbol" : "houxuanren1@qq.com",
                "timestamp" : 1546496753,
                "to_uid" : "ceshixia1@qq.com",
                "vote" : 0
        },
        {
                "address" : "UNR6s87LD9TsG2XrRVFSpWz1yPpv5oN43V",
                "content" : "矿工2",
                "height" : 3053,
                "status" : "registered",
                "symbol" : "houxuanren2@qq.com",
                "timestamp" : 1546496900,
                "to_uid" : "ceshixia2@qq.com",
                "vote" : 0
        },
        {
                "address" : "UkwAarnHiVUoBi4mHupZ3GyLcVLDxPe9eo",
                "content" : "'reward_pool_miner' candidate is issued by reward_pool just to maintain blockchain when there is no any other miner.",
                "height" : 4294967295,
                "status" : "registered",
                "symbol" : "reward_pool_miner",
                "timestamp" : 1550073600,
                "to_uid" : "reward_pool",
                "vote" : 0
        }
]

**Comment by o-u-p** [comment]
Please start testing at UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
The vote field displays is 0
@o-u-p

**Comment by o-u-p** [comment]
Please start testing at UIP0.5_tony @yuyuyu2018 .

**Comment by yuyuyu2018** [comment]
solved
