### ISSUE TITLE
 The quantity of display problems vote【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#277]
![_20190104102305](https://user-images.githubusercontent.com/45030364/50671110-cd348780-100a-11e9-93c6-38634163d0da.png)
[tony@localhost bin]$ ./uc-cli showwallettoken ceshi0103 123456
[
	{
		"address" : "Udhzk2s2AcGzrniNeyC35k5xETDXSXMLyV",
		"decimal_number" : 1,
		"description" : "'BLOCK' token is issued by blackhole.Miners can use it to get reward",
		"issuer" : "BLACKHOLE",
		"locked_quantity" : 0,
		"quantity" : 255902,
		"secondaryissue_threshold" : 0,
		"status" : "unspent",
		"symbol" : "BLOCK"
	},
	{
		"address" : "UZ6Um9zRtucJApQSMGWkbArR5w3ad3RXo4",
		"decimal_number" : 1,
		"description" : "'VOTE' token is issued by blackhole.Users can use it to vote.",
		"issuer" : "BLACKHOLE",
		"locked_quantity" : 0,
		"quantity" : 6,
		"secondaryissue_threshold" : 0,
		"status" : "unspent",
		"symbol" : "VOTE"
	},
	{
		"address" : "Ukw1oe2tnx1gQjx5E6V7GeJfPMYfdtCVmC",
		"decimal_number" : 1,
		"description" : "'VOTE' token is issued by blackhole.Users can use it to vote.",
		"issuer" : "BLACKHOLE",
		"locked_quantity" : 0,
		"quantity" : 5,
		"secondaryissue_threshold" : 0,
		"status" : "unspent",
		"symbol" : "VOTE"
	}
]

this Udhzk2s2AcGzrniNeyC35k5xETDXSXMLyV is startmining now
It will show its quantity in a moment, but it will not show its quantity in a moment.

**Comment by o-u-p** [comment]
Please start testing at UIP0.5_tony @yuyuyu2018 .
