### ISSUE TITLE
UIP0.5 showminers sometimes show nothing[bug]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#278]
Yangs-MacBook-Pro:bin cary$ ./uc-cli showminers
[]
Yangs-MacBook-Pro:bin cary$ ./uc-cli showminers
[
        {
                "address" : "UNfrtAxhJRi83PjTPjV3yNPKnjLYR22Bhx",
                "content" : "",
                "height" : 326,
                "status" : "registered",
                "symbol" : "yangsminer",
                "timestamp" : 1546568671,
                "to_uid" : "yang",
                "vote" : 0
        },
        {
                "address" : "UkwAarnHiVUoBi4mHupZ3GyLcVLDxPe9eo",
                "content" : "'reward_pool_miner' candidate is issued by reward_pool just to maintain blockchain when there is no any other miner.",
                "height" : 4294967295,
                "status" : "registered",
                "symbol" : "reward_pool_miner",
                "timestamp" : 1550073600,
                "to_uid" : "reward_pool",
                "vote" : 0
        }
]

**Comment by o-u-p** [comment]
Please check it at UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
resolved
