### ISSUE TITLE
The same address can transfer candidates again【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#279]
[tony@localhost bin]$ ./uc-cli transfercandidate  ceshi0103-1 123456 ceshi0103dL52@@qq.com houxuanren5
{
	"hash" : "e8017ab8d002b1af17caa11d361acfd734f5200235720afaa0ea81ea487422c3",
	"inputs" : 
	[
		{
			"address" : "UNDnp4UGVSMEuimkpuKvSTrBpMbQXTdL52",
			"previous_output" : 
			{
				"hash" : "455479674da83b4c03e1edbbcbf284a02403a784d16be245a55b8c459567d758",
				"index" : 1
			},
			"script" : "[ 3045022100b7f47d920d387bcb7930cba262e545e5f9656ae0e945f287fc335570dd445add0220292cbd072a134f75140a79b8ec716447033c31583a9aaec0c65b21e74c7efbb101 ] [ 0293e4396b27b04821d4222107a0c44aac5ecf31b8adb1bcaa12f11055ffecd24f ]",
			"sequence" : 4294967295
		},
		{
			"address" : "UNDnp4UGVSMEuimkpuKvSTrBpMbQXTdL52",
			"previous_output" : 
			{
				"hash" : "455479674da83b4c03e1edbbcbf284a02403a784d16be245a55b8c459567d758",
				"index" : 0
			},
			"script" : "[ 3045022100a1b918170b0f09f91bc478fbeb29e83e5761e28c873071b2280d8d325bec4af10220685804bf894360e6793685b44438ba41a97c9b681baa01eab0d7269d1a39cbc701 ] [ 0293e4396b27b04821d4222107a0c44aac5ecf31b8adb1bcaa12f11055ffecd24f ]",
			"sequence" : 4294967295
		}
	],
	"lock_time" : "0",
	"outputs" : 
	[
		{
			"address" : "UNDnp4UGVSMEuimkpuKvSTrBpMbQXTdL52",
			"asset" : 
			{
				"address" : "UNDnp4UGVSMEuimkpuKvSTrBpMbQXTdL52",
				"from_uid" : "ceshi0103dL52@@qq.com",
				"status" : "transfered",
				"symbol" : "houxuanren5",
				"to_uid" : "ceshi0103dL52@@qq.com",
				"type" : "candidate"
			},
			"index" : 0,
			"locked_height_range" : 0,
			"script" : "dup hash160 [ 029ada101233842be24bb6d623a7f0bca5f1467c ] equalverify checksig",
			"value" : 0
		},
		{
			"address" : "UNDnp4UGVSMEuimkpuKvSTrBpMbQXTdL52",
			"asset" : 
			{
				"type" : "ucn"
			},
			"index" : 1,
			"locked_height_range" : 0,
			"script" : "dup hash160 [ 029ada101233842be24bb6d623a7f0bca5f1467c ] equalverify checksig",
			"value" : 49979999600000
		}
	],
	"version" : "4"
}
![qq 20190104110726](https://user-images.githubusercontent.com/45030364/50672115-07a12300-1011-11e9-9699-335774588645.png)

**Comment by o-u-p** [comment]
Please start testing at UIP0.5_tony @yuyuyu2018 .

**Comment by yuyuyu2018** [comment]
transfercandidate the same address for your account have been solved
but can not transfercandidate  the different address for your account

**Comment by yuyuyu2018** [comment]
tony@ubuntu:~/project/wor_pro/uchain-fullnode/build/bin$ ./uc-cli transfercandidate xiaoyuzi 123456 xiaoyuzi2nf4@qq.com houxuanren1
{
	"code" : 4012,
	"message" : "Cannot transfer candidate to self. "
}
@o-u-p

**Comment by yuyuyu2018** [comment]
resolved
