### ISSUE TITLE
deposit commad error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#280]
[tony@localhost bin]$ ./uc-cli showbalances ceshi0103-1 123456
[
	{
		"address" : "UNDnp4UGVSMEuimkpuKvSTrBpMbQXTdL52",
		"available" : 49979999600000,
		"confirmed" : 99979999600000,
		"frozen" : 50000000000000,
		"received" : 399929999400000,
		"unspent" : 99979999600000
	},
	{
		"address" : "Um2kiKU5noUkCNjTVyceWQ7MQrpWXFK3KS",
		"available" : 49980000000000,
		"confirmed" : 99980000000000,
		"frozen" : 50000000000000,
		"received" : 299970000000000,
		"unspent" : 99980000000000
	}
]
[tony@localhost bin]$ ./uc-cli deposit -d 45 -u ceshi0103dL52@@qq.com  ceshi0103-1 123456 100000000 
{
	"code" : 1021,
	"message" : "Parameter cannot be negative."
}

**Comment by yuyuyu2018** [comment]
[tony@localhost bin]$ ./uc-cli vote -r ceshi0104YL2V@@qq.com:1 ceshi0103-1 123456 ceshi0104YeCq@qq.com
{
	"code" : 1021,
	"message" : "Parameter cannot be negative."
}

**Comment by yuyuyu2018** [comment]
[tony@localhost bin]$ ./uc-cli vote -r ceshi0104YeCq@qq.com:1 ceshi0104-1 123456 ceshi0104YL2V@@qq.com
{
	"code" : 1021,
	"message" : "Parameter cannot be negative."
}

**Comment by o-u-p** [comment]
Fixed in UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
It has been proved that the problem has been solved
