### ISSUE TITLE
administrator_required = true，addpeer commands don't work.

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#284]
the preset condition：[server] administrator_required = true

[tony@localhost bin]$ ./uc-cli addpeer -h

Usage: uc-cli addpeer [-h] [--operation value] NODEADDRESS [ADMINNAME]   
[ADMINAUTH]                                                              

Info: This command is used to add/remove p2p node.                       

Options (named):

-h [--help]          Get a description and instructions for this command.
-o [--operation]     The operation[ add|ban ] to the target node address.
                     default: add.                                       

Arguments (positional):

NODEADDRESS          The target node address[x.x.x.x:port].              
ADMINNAME            admin name.                                         
ADMINAUTH            admin password/authorization.                       

[tony@localhost bin]$ ./uc-cli addpeer 192.168.16.128:5682
success
[tony@localhost bin]$ ./uc-cli showpeers
{
	"code" : 3002,
	"message" : "Administrator name must be [administerator],incorrect vocabulary @_@."
}
[tony@localhost bin]$ ./uc-cli showpeers administerator ucgo
[
	"116.62.238.230:5682",
	"120.78.209.248:5682",
	"112.74.181.29:5682",
	"13.124.250.27:5682",
	"192.168.16.169:49008",
	"192.168.16.169:5682"
]

**Comment by o-u-p** [comment]
Please start testing at UIP0.5_tony @yuyuyu2018 .

**Comment by yuyuyu2018** [comment]
solved
