### ISSUE TITLE
apppeer prompt error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#285]
[tony@localhost bin]$ ./uc-cli addpeer 192.168.16.128:5682
success
Success should not be prompted

because this 192.168.16.128 is closed

**Comment by yuyuyu2018** [comment]
[tony@localhost bin]$ ./uc-cli showpeers administerator ucgo
[
	"116.62.238.230:5682",
	"120.78.209.248:5682",
	"112.74.181.29:5682",
	"13.124.250.27:5682",
	"192.168.16.169:49008",
	"192.168.16.169:5682"
]

**Comment by o-u-p** [comment]
Please start testing at UIP0.5_tony @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
no problem
