### ISSUE TITLE
mining uid transferuid error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#289]
tony@ubuntu:~/project/wor_pro/uchain-fullnode/build/bin$ ./uc-cli transferuid xiaoyuzi1 123456 UgCh5VJa35A6sXmob6akYT8bb7DBWkmqdb xiaoyuzi11@qq.com
{
	"code" : 5304,
	"message" : "validate transaction failure. Transaction:\n\tversion = 4\n\tlocktime = 0\nInputs:\n\thash = 4c3189c68fee70641d6860d279508f1bc3fe00f0fed5b7d93ceeb961ff7aac3d\n\tindex = 0\n\t[ 304402200441dcbcf4019bd414f47180d71afa4a200e49c64a6e4279cd50487a9afe5dbf022014e79f8de420a3a1695c264553e0e8a584534c0d06992f119f4043c8c0fb063d01 ] [ 025685a73c2cefb4f0da43c3c79efa2e5f61cfa539dc023b4eb8616298a1278379 ]\n\tsequence = 4294967295\n\thash = 5208d6e65177af4f211a49e15edb772fdf43663bc29b603d08c72eaba4c6553c\n\tindex = 0\n\t[ 3045022100a40015a965945ea671cd0c6e0eed7480e83b696f7eb6b555c5eeb82793c42c340220785a35206aaa25bf98c55cbd5940503a6e96a27e3f7bf28828cab4e1382d2afc01 ] [ 02278fe4fc6a8075c99b6d449cdab2e340966e2e6e468e7f9cf7d99bf20dd3c1a1 ]\n\tsequence = 4294967295\nOutputs:\n\tvalue = 0\n\tdup hash160 [ c7d7e9d81e760ce1f855e0fc0da7f68017ac7c8e ] equalverify checksig\n\t\t version = 1\n\t type = 4\n\t status = 2\n\t symbol = xiaoyuzi11@qq.com\n\t address = UgCh5VJa35A6sXmob6akYT8bb7DBWkmqdb\n\n\tvalue = 800000\n\tdup hash160 [ c7d7e9d81e760ce1f855e0fc0da7f68017ac7c8e ] equalverify checksig\n\t\t version = 1\n\t type = 0\n\t value = 800000\n\n\n"
}

**Comment by o-u-p** [comment]
It's the common behavior if validate transaction failure @yuyuyu2018  .

**Comment by yuyuyu2018** [comment]
have been solved
