### ISSUE TITLE
more than once mining is permitted.[bug]

### ISSUE THREAD

**Issue by o-u-p** [UCHAIN-WORLD/uchain-fullnode#45]
![screenshot from 2018-11-07 13-30-20](https://user-images.githubusercontent.com/22117027/48112410-5476b080-e291-11e8-9b35-ff6fd15c843b.png)

**Comment by yangguanglu** [comment]
342c7db532797853a9166b99cfc0b2cfaa22a886 fixed

**Comment by yangguanglu** [comment]
@yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
