### ISSUE TITLE
when synchronize block it always stuck after some time[bug]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#47]
a very big problem needed to be solved soon

**Comment by yangguanglu** [comment]
20181108T101158 INFO [blockchain] Block [30075] verified in (0) secs or (0) ms/input
20181108T101158 INFO [blockchain] Block [30076] verify (1) txs and (1) inputs
20181108T101158 INFO [blockchain] Block [30076] verified in (0) secs or (0) ms/input
20181108T101158 INFO [blockchain] Block [30077] verify (1) txs and (1) inputs
20181108T101158 INFO [blockchain] Block [30077] verified in (0) secs or (0) ms/input
20181108T101158 INFO [blockchain] Block [30078] verify (1) txs and (1) inputs
20181108T101158 INFO [blockchain] Block [30078] verified in (0) secs or (0) ms/input
^C20181108T101533 INFO [ucd] Stop signal detected (code: 2).
20181108T101533 INFO [ucd] Please wait while the server is stopping...
20181108T101534 INFO [http] Http Service Stopped.
20181108T101535 INFO [mgserver] Websocket Service Stopped.
20181108T101542 INFO [node] Server stopped successfully.
it costs 294 seconds, rx,14053393, tx,1160998
localhost:bin cary$ ./ucd
20181108T101809 INFO [ucd] Ucd version is 0.0.1
20181108T101809 INFO [ucd] Using config file: "/Users/cary/Library/Application Support/UChain/uc.conf"
20181108T101809 INFO [ucd] Please wait while the server is starting...
20181108T101809 INFO [node] Starting manual session.
20181108T101809 INFO [ucd] Seeding is complete.
20181108T101809 INFO [http] Http Service listen on 0.0.0.0:8820
20181108T101809 INFO [mgserver] Websocket Service listen on 0.0.0.0:8821
20181108T101809 INFO [node] Node start height is (30073).
20181108T101809 INFO [node] Starting inbound session.
20181108T101809 INFO [node] Starting outbound session.
20181108T101809 INFO [ucd] Bound public query service to tcp://*:18707
20181108T101809 INFO [ucd] Server is started.

**Comment by yangguanglu** [comment]
fixed 9bc40d1bbaf56d76e29bcc01719670759f49c6ed @yuyuyu2018

**Comment by yangguanglu** [comment]
fixed @yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
