### ISSUE TITLE
when stop synchronized block ,restart the block height is not the same with the stop height[bug]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#48]
20181108T102446 INFO [blockchain] Block [31157] verify (1) txs and (1) inputs
20181108T102446 INFO [blockchain] Block [31157] verified in (0) secs or (0) ms/input
20181108T102446 INFO [blockchain] Block [31158] verify (1) txs and (1) inputs
20181108T102446 INFO [blockchain] Block [31158] verified in (0) secs or (0) ms/input
20181108T102446 INFO [blockchain] Block [31159] verify (1) txs and (1) inputs
20181108T102446 INFO [blockchain] Block [31159] verified in (0) secs or (0) ms/input
20181108T102446 INFO [blockchain] Block [31160] verify (1) txs and (1) inputs
20181108T102446 INFO [blockchain] Block [31160] verified in (0) secs or (0) ms/input
^C20181108T102839 INFO [ucd] Stop signal detected (code: 2).
20181108T102839 INFO [ucd] Please wait while the server is stopping...
20181108T102840 INFO [http] Http Service Stopped.
20181108T102840 INFO [mgserver] Websocket Service Stopped.
20181108T102842 INFO [node] Server stopped successfully.
it costs 259 seconds, rx,624508, tx,351385
localhost:bin cary$ ./ucd
20181108T102843 INFO [ucd] Ucd version is 0.0.1
20181108T102843 INFO [ucd] Using config file: "/Users/cary/Library/Application Support/UChain/uc.conf"
20181108T102843 INFO [ucd] Please wait while the server is starting...
20181108T102843 INFO [node] Starting manual session.
20181108T102843 INFO [ucd] Seeding is complete.
20181108T102843 INFO [http] Http Service listen on 0.0.0.0:8820
20181108T102843 INFO [mgserver] Websocket Service listen on 0.0.0.0:8821
20181108T102843 INFO [node] Node start height is (31143).
20181108T102843 INFO [node] Starting inbound session.
20181108T102843 INFO [node] Starting outbound session.
20181108T102843 INFO [ucd] Bound public query service to tcp://*:18707
20181108T102843 INFO [ucd] Server is started.
20181108T102851 INFO [upnp] No valid UPnP IGDs found

**Comment by o-u-p** [comment]
It seems the height  value in console will be printed before it is stored in the database, every validation int the console has a single thread to verify, so if the process stopped when the block data hasn't stored in the database and it just showed int the console, it would show something like this.

**Comment by yangguanglu** [comment]
fixed @yuyuyu2018

**Comment by yuyuyu2018** [comment]
Unresolved

**Comment by yangguanglu** [comment]
fixed @yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
