### ISSUE TITLE
always fork when synchronize block[bug]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#49]
0181108T111359 DEBUG [blockchain]  push block height:33407 hash:778031485fe4731639bc6cc4353af8533201bde94b4cb966ed67a5b851c891c8
20181108T111359 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33406) new blocks (1) replace blocks (0)
20181108T111359 DEBUG [blockchain] Orphan pool added block [9223b0709dacd273b21e61bae42342e0b51eedddf7ed9229a631ee4cac151ea5] previous [778031485fe4731639bc6cc4353af8533201bde94b4cb966ed67a5b851c891c8] old size (0).
20181108T111359 INFO [blockchain] Block [33408] verify (1) txs and (1) inputs
20181108T111359 INFO [blockchain] Block [33408] verified in (0) secs or (0) ms/input
20181108T111359 DEBUG [blockchain] Orphan pool removed block [9223b0709dacd273b21e61bae42342e0b51eedddf7ed9229a631ee4cac151ea5] old size (1). with status: success
20181108T111359 DEBUG [blockchain]  push block height:33408 hash:9223b0709dacd273b21e61bae42342e0b51eedddf7ed9229a631ee4cac151ea5
20181108T111359 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33407) new blocks (1) replace blocks (0)
20181108T111359 DEBUG [blockchain] Orphan pool added block [7a228677cdb265b4e0e19e4bb0c43d91b30ddd078ca451b4e46ef0adbf325665] previous [9223b0709dacd273b21e61bae42342e0b51eedddf7ed9229a631ee4cac151ea5] old size (0).
20181108T111359 INFO [blockchain] Block [33409] verify (1) txs and (1) inputs
20181108T111359 INFO [blockchain] Block [33409] verified in (0) secs or (0) ms/input
20181108T111359 DEBUG [blockchain] Orphan pool removed block [7a228677cdb265b4e0e19e4bb0c43d91b30ddd078ca451b4e46ef0adbf325665] old size (1). with status: success
20181108T111359 DEBUG [blockchain]  push block height:33409 hash:7a228677cdb265b4e0e19e4bb0c43d91b30ddd078ca451b4e46ef0adbf325665
20181108T111359 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33408) new blocks (1) replace blocks (0)
20181108T111400 DEBUG [blockchain] Orphan pool added block [6f1517ef172b332c879f9ca3a5ecc08e0a4e640fe6895b70948cae11041075cb] previous [7a228677cdb265b4e0e19e4bb0c43d91b30ddd078ca451b4e46ef0adbf325665] old size (0).
20181108T111400 INFO [blockchain] Block [33410] verify (1) txs and (1) inputs
20181108T111400 INFO [blockchain] Block [33410] verified in (0) secs or (0) ms/input
20181108T111400 DEBUG [blockchain] Orphan pool removed block [6f1517ef172b332c879f9ca3a5ecc08e0a4e640fe6895b70948cae11041075cb] old size (1). with status: success
20181108T111400 DEBUG [blockchain]  push block height:33410 hash:6f1517ef172b332c879f9ca3a5ecc08e0a4e640fe6895b70948cae11041075cb
20181108T111400 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33409) new blocks (1) replace blocks (0)
20181108T111400 DEBUG [blockchain] Orphan pool added block [35447f9fbfdffcc72fbaf37feb9d0710389dafc9fec04cffc18d641045a1b5d7] previous [6f1517ef172b332c879f9ca3a5ecc08e0a4e640fe6895b70948cae11041075cb] old size (0).
20181108T111400 INFO [blockchain] Block [33411] verify (1) txs and (1) inputs
20181108T111400 INFO [blockchain] Block [33411] verified in (0) secs or (0) ms/input
20181108T111400 DEBUG [blockchain] Orphan pool removed block [35447f9fbfdffcc72fbaf37feb9d0710389dafc9fec04cffc18d641045a1b5d7] old size (1). with status: success
20181108T111400 DEBUG [blockchain]  push block height:33411 hash:35447f9fbfdffcc72fbaf37feb9d0710389dafc9fec04cffc18d641045a1b5d7
20181108T111400 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33410) new blocks (1) replace blocks (0)
20181108T111401 DEBUG [blockchain] Orphan pool added block [917b29f3735fd536f31564dc452065ff8b3335edbf0a2dbf2c14d5bdfa87c37a] previous [35447f9fbfdffcc72fbaf37feb9d0710389dafc9fec04cffc18d641045a1b5d7] old size (0).
20181108T111401 INFO [blockchain] Block [33412] verify (1) txs and (1) inputs
20181108T111401 INFO [blockchain] Block [33412] verified in (0) secs or (0) ms/input
20181108T111401 DEBUG [blockchain] Orphan pool removed block [917b29f3735fd536f31564dc452065ff8b3335edbf0a2dbf2c14d5bdfa87c37a] old size (1). with status: success
20181108T111401 DEBUG [blockchain]  push block height:33412 hash:917b29f3735fd536f31564dc452065ff8b3335edbf0a2dbf2c14d5bdfa87c37a
20181108T111401 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33411) new blocks (1) replace blocks (0)
20181108T111402 DEBUG [blockchain] Orphan pool added block [92fa54d6bd2dd4311f87836f028bc18bd8d49b668d6ca5ca99359cd285984304] previous [917b29f3735fd536f31564dc452065ff8b3335edbf0a2dbf2c14d5bdfa87c37a] old size (0).
20181108T111402 INFO [blockchain] Block [33413] verify (1) txs and (1) inputs
20181108T111402 INFO [blockchain] Block [33413] verified in (0) secs or (0) ms/input
20181108T111402 DEBUG [blockchain] Orphan pool removed block [92fa54d6bd2dd4311f87836f028bc18bd8d49b668d6ca5ca99359cd285984304] old size (1). with status: success
20181108T111402 DEBUG [blockchain]  push block height:33413 hash:92fa54d6bd2dd4311f87836f028bc18bd8d49b668d6ca5ca99359cd285984304
20181108T111402 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33412) new blocks (1) replace blocks (0)
20181108T111402 DEBUG [blockchain] Orphan pool added block [7eaf4122863ff1f2ffe117a46a1783f9497f13949feb382713bbb28ae1a1aa0f] previous [92fa54d6bd2dd4311f87836f028bc18bd8d49b668d6ca5ca99359cd285984304] old size (0).
20181108T111402 INFO [blockchain] Block [33414] verify (1) txs and (1) inputs
20181108T111402 INFO [blockchain] Block [33414] verified in (0) secs or (0) ms/input
20181108T111402 DEBUG [blockchain] Orphan pool removed block [7eaf4122863ff1f2ffe117a46a1783f9497f13949feb382713bbb28ae1a1aa0f] old size (1). with status: success
20181108T111402 DEBUG [blockchain]  push block height:33414 hash:7eaf4122863ff1f2ffe117a46a1783f9497f13949feb382713bbb28ae1a1aa0f
20181108T111402 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33413) new blocks (1) replace blocks (0)
20181108T111409 DEBUG [blockchain] Orphan pool added block [3b8edb6958f0f1106f4bf834f9928932e80a0006d63cd6c30eda4f013b4046e7] previous [7eaf4122863ff1f2ffe117a46a1783f9497f13949feb382713bbb28ae1a1aa0f] old size (0).
20181108T111409 INFO [blockchain] Block [33415] verify (1) txs and (1) inputs
20181108T111409 INFO [blockchain] Block [33415] verified in (0) secs or (0) ms/input
20181108T111409 DEBUG [blockchain] Orphan pool removed block [3b8edb6958f0f1106f4bf834f9928932e80a0006d63cd6c30eda4f013b4046e7] old size (1). with status: success
20181108T111409 DEBUG [blockchain]  push block height:33415 hash:3b8edb6958f0f1106f4bf834f9928932e80a0006d63cd6c30eda4f013b4046e7
20181108T111409 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33414) new blocks (1) replace blocks (0)
20181108T111409 DEBUG [blockchain] Orphan pool added block [2f8c8c422ec8c8502c8dc6816b528cbff3181e8090e7e0a0804efedef1909977] previous [3b8edb6958f0f1106f4bf834f9928932e80a0006d63cd6c30eda4f013b4046e7] old size (0).
20181108T111409 INFO [blockchain] Block [33416] verify (1) txs and (1) inputs
20181108T111409 INFO [blockchain] Block [33416] verified in (0) secs or (0) ms/input
20181108T111409 DEBUG [blockchain] Orphan pool removed block [2f8c8c422ec8c8502c8dc6816b528cbff3181e8090e7e0a0804efedef1909977] old size (1). with status: success
20181108T111409 DEBUG [blockchain]  push block height:33416 hash:2f8c8c422ec8c8502c8dc6816b528cbff3181e8090e7e0a0804efedef1909977
20181108T111409 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33415) new blocks (1) replace blocks (0)
20181108T111410 DEBUG [blockchain] Orphan pool added block [a3865272fb672bcb9b8df78ad6c3ac52940a9affbb5a5baf221bc0256733f2ca] previous [2f8c8c422ec8c8502c8dc6816b528cbff3181e8090e7e0a0804efedef1909977] old size (0).
20181108T111410 INFO [blockchain] Block [33417] verify (1) txs and (1) inputs
20181108T111410 INFO [blockchain] Block [33417] verified in (0) secs or (0) ms/input
20181108T111410 DEBUG [blockchain] Orphan pool removed block [a3865272fb672bcb9b8df78ad6c3ac52940a9affbb5a5baf221bc0256733f2ca] old size (1). with status: success
20181108T111410 DEBUG [blockchain]  push block height:33417 hash:a3865272fb672bcb9b8df78ad6c3ac52940a9affbb5a5baf221bc0256733f2ca
20181108T111410 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33416) new blocks (1) replace blocks (0)
20181108T111410 DEBUG [blockchain] Orphan pool added block [ca0a326ec9e1b57b6a82cb89aa6ce237ee6ef042e4ceb22fd72d46c9a00d3288] previous [a3865272fb672bcb9b8df78ad6c3ac52940a9affbb5a5baf221bc0256733f2ca] old size (0).
20181108T111410 INFO [blockchain] Block [33418] verify (1) txs and (1) inputs
20181108T111410 INFO [blockchain] Block [33418] verified in (0) secs or (0) ms/input
20181108T111410 DEBUG [blockchain] Orphan pool removed block [ca0a326ec9e1b57b6a82cb89aa6ce237ee6ef042e4ceb22fd72d46c9a00d3288] old size (1). with status: success
20181108T111410 DEBUG [blockchain]  push block height:33418 hash:ca0a326ec9e1b57b6a82cb89aa6ce237ee6ef042e4ceb22fd72d46c9a00d3288
20181108T111410 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33417) new blocks (1) replace blocks (0)
20181108T111411 DEBUG [blockchain] Orphan pool added block [1153553dc5fd9cf03931bc9cf22536d9df82012feb3bdb5558b50e26d42e8ffb] previous [ca0a326ec9e1b57b6a82cb89aa6ce237ee6ef042e4ceb22fd72d46c9a00d3288] old size (0).
20181108T111411 INFO [blockchain] Block [33419] verify (1) txs and (1) inputs
20181108T111411 INFO [blockchain] Block [33419] verified in (0) secs or (0) ms/input
20181108T111411 DEBUG [blockchain] Orphan pool removed block [1153553dc5fd9cf03931bc9cf22536d9df82012feb3bdb5558b50e26d42e8ffb] old size (1). with status: success
20181108T111411 DEBUG [blockchain]  push block height:33419 hash:1153553dc5fd9cf03931bc9cf22536d9df82012feb3bdb5558b50e26d42e8ffb
20181108T111411 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33418) new blocks (1) replace blocks (0)
20181108T111411 DEBUG [blockchain] Orphan pool added block [57964ef028c8d0e162b2d855118d70507f893e770b71a5cdf9d9e523f36b8064] previous [1153553dc5fd9cf03931bc9cf22536d9df82012feb3bdb5558b50e26d42e8ffb] old size (0).
20181108T111411 INFO [blockchain] Block [33420] verify (1) txs and (1) inputs
20181108T111411 INFO [blockchain] Block [33420] verified in (0) secs or (0) ms/input
20181108T111411 DEBUG [blockchain] Orphan pool removed block [57964ef028c8d0e162b2d855118d70507f893e770b71a5cdf9d9e523f36b8064] old size (1). with status: success
20181108T111411 DEBUG [blockchain]  push block height:33420 hash:57964ef028c8d0e162b2d855118d70507f893e770b71a5cdf9d9e523f36b8064
20181108T111411 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33419) new blocks (1) replace blocks (0)
20181108T111419 DEBUG [blockchain] Orphan pool added block [2fb43c25b21bca3d98cef63610f701fb8fc4d68bb53f807490827dddde70e624] previous [57964ef028c8d0e162b2d855118d70507f893e770b71a5cdf9d9e523f36b8064] old size (0).
20181108T111419 INFO [blockchain] Block [33421] verify (1) txs and (1) inputs
20181108T111419 INFO [blockchain] Block [33421] verified in (0) secs or (0) ms/input
20181108T111419 DEBUG [blockchain] Orphan pool removed block [2fb43c25b21bca3d98cef63610f701fb8fc4d68bb53f807490827dddde70e624] old size (1). with status: success
20181108T111419 DEBUG [blockchain]  push block height:33421 hash:2fb43c25b21bca3d98cef63610f701fb8fc4d68bb53f807490827dddde70e624
20181108T111419 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33420) new blocks (1) replace blocks (0)
20181108T111419 DEBUG [blockchain] Orphan pool added block [f0259e90fd690f7b7aaaf138fab2e4245048bafd87761559c3c1a59bbabe0ef4] previous [2fb43c25b21bca3d98cef63610f701fb8fc4d68bb53f807490827dddde70e624] old size (0).
20181108T111419 INFO [blockchain] Block [33422] verify (1) txs and (1) inputs
20181108T111419 INFO [blockchain] Block [33422] verified in (0) secs or (0) ms/input
20181108T111419 DEBUG [blockchain] Orphan pool removed block [f0259e90fd690f7b7aaaf138fab2e4245048bafd87761559c3c1a59bbabe0ef4] old size (1). with status: success
20181108T111419 DEBUG [blockchain]  push block height:33422 hash:f0259e90fd690f7b7aaaf138fab2e4245048bafd87761559c3c1a59bbabe0ef4
20181108T111419 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33421) new blocks (1) replace blocks (0)
20181108T111419 DEBUG [blockchain] Orphan pool added block [ca67fb2089134452470b3336ac69a3ecc623f31656952d30dcb108eeba9b1367] previous [f0259e90fd690f7b7aaaf138fab2e4245048bafd87761559c3c1a59bbabe0ef4] old size (0).
20181108T111419 INFO [blockchain] Block [33423] verify (1) txs and (1) inputs
20181108T111419 INFO [blockchain] Block [33423] verified in (0) secs or (0) ms/input
20181108T111419 DEBUG [blockchain] Orphan pool removed block [ca67fb2089134452470b3336ac69a3ecc623f31656952d30dcb108eeba9b1367] old size (1). with status: success
20181108T111419 DEBUG [blockchain]  push block height:33423 hash:ca67fb2089134452470b3336ac69a3ecc623f31656952d30dcb108eeba9b1367
20181108T111419 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33422) new blocks (1) replace blocks (0)
20181108T111419 DEBUG [blockchain] Orphan pool added block [bb5dab5ac8f92aae37321a8d5280c6f52fea0572e7288baedda04ebb4b21e132] previous [ca67fb2089134452470b3336ac69a3ecc623f31656952d30dcb108eeba9b1367] old size (0).
20181108T111419 INFO [blockchain] Block [33424] verify (1) txs and (1) inputs
20181108T111419 INFO [blockchain] Block [33424] verified in (0) secs or (0) ms/input
20181108T111419 DEBUG [blockchain] Orphan pool removed block [bb5dab5ac8f92aae37321a8d5280c6f52fea0572e7288baedda04ebb4b21e132] old size (1). with status: success
20181108T111419 DEBUG [blockchain]  push block height:33424 hash:bb5dab5ac8f92aae37321a8d5280c6f52fea0572e7288baedda04ebb4b21e132
20181108T111419 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33423) new blocks (1) replace blocks (0)
20181108T111420 DEBUG [blockchain] Orphan pool added block [2cc2e8da0a96e33f837de0924c13e89f05279914b0d5c8014ed440e7677fde1f] previous [bb5dab5ac8f92aae37321a8d5280c6f52fea0572e7288baedda04ebb4b21e132] old size (0).
20181108T111420 INFO [blockchain] Block [33425] verify (1) txs and (1) inputs
20181108T111420 INFO [blockchain] Block [33425] verified in (0) secs or (0) ms/input
20181108T111420 DEBUG [blockchain] Orphan pool removed block [2cc2e8da0a96e33f837de0924c13e89f05279914b0d5c8014ed440e7677fde1f] old size (1). with status: success
20181108T111420 DEBUG [blockchain]  push block height:33425 hash:2cc2e8da0a96e33f837de0924c13e89f05279914b0d5c8014ed440e7677fde1f
20181108T111420 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33424) new blocks (1) replace blocks (0)
20181108T111420 DEBUG [blockchain] Orphan pool added block [f233bca1044c545c14c6fc10194c1c5c011539c2a50515459ff60c3b34479f5d] previous [2cc2e8da0a96e33f837de0924c13e89f05279914b0d5c8014ed440e7677fde1f] old size (0).
20181108T111420 INFO [blockchain] Block [33426] verify (1) txs and (1) inputs
20181108T111420 INFO [blockchain] Block [33426] verified in (0) secs or (0) ms/input
20181108T111420 DEBUG [blockchain] Orphan pool removed block [f233bca1044c545c14c6fc10194c1c5c011539c2a50515459ff60c3b34479f5d] old size (1). with status: success
20181108T111420 DEBUG [blockchain]  push block height:33426 hash:f233bca1044c545c14c6fc10194c1c5c011539c2a50515459ff60c3b34479f5d
20181108T111420 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33425) new blocks (1) replace blocks (0)
20181108T111421 DEBUG [blockchain] Orphan pool added block [653493259f82c3b2aa8b372fc83add2ea80029454c9108856479a70ee27f3648] previous [f233bca1044c545c14c6fc10194c1c5c011539c2a50515459ff60c3b34479f5d] old size (0).
20181108T111421 INFO [blockchain] Block [33427] verify (1) txs and (1) inputs
20181108T111421 INFO [blockchain] Block [33427] verified in (0) secs or (0) ms/input
20181108T111421 DEBUG [blockchain] Orphan pool removed block [653493259f82c3b2aa8b372fc83add2ea80029454c9108856479a70ee27f3648] old size (1). with status: success
20181108T111421 DEBUG [blockchain]  push block height:33427 hash:653493259f82c3b2aa8b372fc83add2ea80029454c9108856479a70ee27f3648
20181108T111421 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33426) new blocks (1) replace blocks (0)
20181108T111422 DEBUG [blockchain] Orphan pool added block [6b66ac5e93ceeeb945437597b891dbc56db6437f71d97df74d171021d77c161b] previous [653493259f82c3b2aa8b372fc83add2ea80029454c9108856479a70ee27f3648] old size (0).
20181108T111422 INFO [blockchain] Block [33428] verify (1) txs and (1) inputs
20181108T111422 INFO [blockchain] Block [33428] verified in (0) secs or (0) ms/input
20181108T111422 DEBUG [blockchain] Orphan pool removed block [6b66ac5e93ceeeb945437597b891dbc56db6437f71d97df74d171021d77c161b] old size (1). with status: success
20181108T111422 DEBUG [blockchain]  push block height:33428 hash:6b66ac5e93ceeeb945437597b891dbc56db6437f71d97df74d171021d77c161b
20181108T111422 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33427) new blocks (1) replace blocks (0)
20181108T111422 DEBUG [blockchain] Orphan pool added block [ba7970cf86cd3b1c516dff2464dc58344c4cee447d97e3ab2f834bc6ec02aacf] previous [6b66ac5e93ceeeb945437597b891dbc56db6437f71d97df74d171021d77c161b] old size (0).
20181108T111422 INFO [blockchain] Block [33429] verify (1) txs and (1) inputs
20181108T111422 INFO [blockchain] Block [33429] verified in (0) secs or (0) ms/input
20181108T111422 DEBUG [blockchain] Orphan pool removed block [ba7970cf86cd3b1c516dff2464dc58344c4cee447d97e3ab2f834bc6ec02aacf] old size (1). with status: success
20181108T111422 DEBUG [blockchain]  push block height:33429 hash:ba7970cf86cd3b1c516dff2464dc58344c4cee447d97e3ab2f834bc6ec02aacf
20181108T111422 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33428) new blocks (1) replace blocks (0)
20181108T111423 DEBUG [blockchain] Orphan pool added block [c5e0ab0db1d3ee94fd4a099b92e3400ed25a6fd431b8c090137437a3c0bf8b49] previous [ba7970cf86cd3b1c516dff2464dc58344c4cee447d97e3ab2f834bc6ec02aacf] old size (0).
20181108T111423 INFO [blockchain] Block [33430] verify (1) txs and (1) inputs
20181108T111423 INFO [blockchain] Block [33430] verified in (0) secs or (0) ms/input
20181108T111423 DEBUG [blockchain] Orphan pool removed block [c5e0ab0db1d3ee94fd4a099b92e3400ed25a6fd431b8c090137437a3c0bf8b49] old size (1). with status: success
20181108T111423 DEBUG [blockchain]  push block height:33430 hash:c5e0ab0db1d3ee94fd4a099b92e3400ed25a6fd431b8c090137437a3c0bf8b49
20181108T111423 DEBUG [blockchain] Reorganize: tx pool size (0) forked at (33429) new blocks (1) replace blocks (0)
20181108T111423 DEBUG [blockchain] Orphan pool added block [9a4ae3ff446245c3c7bba3c069515d8a9fd62f30cb1706fdda3c0fb6b16c5244] previous [c5e0ab0db1d3ee94fd4a099b92e3400ed25a6fd431b8c090137437a3c0bf8b49] old size (0).

**Comment by o-u-p** [comment]
It should be fixed, please start testing @yuyuyu2018

**Comment by yangguanglu** [comment]
fixed @yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
