### ISSUE TITLE
deposit test[test]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#51]
deposit test height: {1728000, 7776000, 20736000, 41472000, 93312000};
deposit rewards: {300000, 1990000, 5200000, 10000000, 24000000};

check if the logic is correct

**Comment by yangguanglu** [comment]
@o-u-p

**Comment by yangguanglu** [comment]
test @yuyuyu2018

**Comment by yuyuyu2018** [comment]
Already tested
