### ISSUE TITLE
The height field is not displayed and the difficulty field is not required.[bug]

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#58]
Both the showinfo command and the showmininginfo command have this problem.
As a result
![20181115114023](https://user-images.githubusercontent.com/45030364/48528856-a5a72580-e8cb-11e8-9377-04d92f26bea3.png)
![20181115114056](https://user-images.githubusercontent.com/45030364/48528864-ab9d0680-e8cb-11e8-9e01-887935ccb76a.png)

**Comment by yangguanglu** [comment]
e3e456cac66cc5053fd63664ee12c979289e38cb fixed @yuyuyu2018

**Comment by yuyuyu2018** [comment]
difficulty field not deleted

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
