### ISSUE TITLE
Sendrawtx command execution error [bug]

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#63]
tony@ubuntu:~$ uc-cli sendrawtx 040000000107a415d81983cad794a5360ae65ef4920856668b15efd433d44aa01801a7d54800000000920047304402200c9a90fe366919124f9508044b518c7619f3a68a3cf2569efb468f53a7485bae0220253a8932ed89994cd557967d6e8393bb0e5c6e9ccf323a94f24ca7625f524b27014c475221034ead1a3f9a596aeaf20bb0f0b1523f6ef0ecce08680c1ffab31b456e03f3d8762103fb1e73da4a233f71d3d612c57820455ebead869686aaecf2156800d9eb8f666a52aeffffffff0240420f00000000001976a914353a7701c6201f641faaeb369ad504438af48a0588ac0100000000000000301b0f000000000017a91489af01eb5f3f15cb56f5096676b6f5e05dad720a87010000000000000000000000
{
	"code" : 5304,
	"message" : "validate transaction failure"
}

**Comment by yuyuyu2018** [comment]
Problems under multitx

**Comment by o-u-p** [comment]
follow the step:
1. execute checkpublickey get public key of the address;
2. every sender execute createmultisigaddress command to get the same multi-signed address.
3. one of execute 'createmultisigtx' to create a multi-signed transaction.
4. every sender execute 'signmultisigtx' ;
5. signmultisigtx

**Comment by yuyuyu2018** [comment]
Operate the command again. This is not a problem.
