### ISSUE TITLE
destroy command execution error [bug]

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#64]
tony@ubuntu:~$ uc-cli destroy xiaoyu 123456 BLOCK 100 
{
	"code" : 1020,
	"message" : "'sendtoken' is not a command. Enter 'help' for a list of commands."
}

**Comment by o-u-p** [comment]
It should be fixed, please start testing in dev_tony2 branch @yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
