### ISSUE TITLE
It is not mine address that can also mine【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#68]
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli showminers
[
	"UkRYvsnfJkwSTAUCcZnqCK8sE1ZYJP6so7"
]
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli startmining -a UNkBgeBnCnjSdB9qRxwmsQ5jseyrZErHM8 yujiali1 12345
solo mining started at UNkBgeBnCnjSdB9qRxwmsQ5jseyrZErHM8
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli startmining -a UNkBgeBnCnjSdB9qRxwmsQ5jseyrZErHM8 yujiali1 12345
{
	"code" : 1024,
	"message" : "Currently mining, please use command <stopmining> to stop the running mining."
}

**Comment by o-u-p** [comment]
It should be fixed, please start testing @yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
