### ISSUE TITLE
 The sendfrom command prompt error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#69]
"address" : "3EF29ZMWp6iDdYcyMPCwYKgkm6wMDr9KPo",
		"available" : 2505964,
		"confirmed" : 2505964,
		"frozen" : 0,
		"received" : 2505964,
		"unspent" : 2505964
	},
	{
		"address" : "UWeVjsMSNHboXVvKgz31sgRSVkEXeNCz6v",
		"available" : 1003809997,
		"confirmed" : 1013809997,
		"frozen" : 10000000,
		"received" : 1029457979,
		"unspent" : 1013809997
	}
]
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli sendfrom -c 3EF29ZMWp6iDdYcyMPCwYKgkm6wMDr9KPo -f 20000 tony1 123456  3EF29ZMWp6iDdYcyMPCwYKgkm6wMDr9KPo Ub9Utbs3hHMharWZBenvU8TjbygAXNtD5L 2000000
{
	"code" : 5302,
	"message" : "not enough ucn or token in from address, or you do not own the from address!"
}

**Comment by o-u-p** [comment]
Should be fixed in dev_tony2, please start testing @yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
