### ISSUE TITLE
After the sendfrom command -c specifies an address, this address receives only a portion of the change amount.【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#70]
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli showbalances xiaoyu 123456
[
	{
		"address" : "USAjibU3hBeC8H4kxGYpSdFH5doprCGcY9",
		"available" : 0,
		"confirmed" : 0,
		"frozen" : 0,
		"received" : 0,
		"unspent" : 0
	},
	{
		"address" : "USqTomALhQ6r2gF2b35FW6vTtXZ2Wexqsu",
		"available" : 70000,
		"confirmed" : 160270,
		"frozen" : 90270,
		"received" : 2540266,
		"unspent" : 160270
	}
]

tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli sendfrom -c USAjibU3hBeC8H4kxGYpSdFH5doprCGcY9 -f 20000 xiaoyu 123456 USqTomALhQ6r2gF2b35FW6vTtXZ2Wexqsu UaBcFRgGtCD7sMwb1v7W2hAGWZS4DKBrcZ 20000

tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli showbalances xiaoyu 123456
[
	{
		"address" : "USAjibU3hBeC8H4kxGYpSdFH5doprCGcY9",
		"available" : 29998,
		"confirmed" : 29998,
		"frozen" : 0,
		"received" : 29998,
		"unspent" : 29998
	},
	{
		"address" : "USqTomALhQ6r2gF2b35FW6vTtXZ2Wexqsu",
		"available" : 2,
		"confirmed" : 90272,
		"frozen" : 90270,
		"received" : 2540266,
		"unspent" : 90272
	}
]

**Comment by o-u-p** [comment]
no problem found, please check again @yuyuyu2018

**Comment by yuyuyu2018** [comment]
You have to look at output in terms of hash value
