### ISSUE TITLE
After the SendTo command specifies the change address, the change address is not received.【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#71]
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli showbalances yujiali3 123456
[
	{
		"address" : "UWeSjd1ve5AZ14EVEKLfRYpuzApoauzLSV",
		"available" : 0,
		"confirmed" : 0,
		"frozen" : 0,
		"received" : 0,
		"unspent" : 0
	},
	{
		"address" : "UVjsbgzEQZqqN3sM3MXrHwjvQ1MQggiXf9",
		"available" : 0,
		"confirmed" : 0,
		"frozen" : 0,
		"received" : 0,
		"unspent" : 0
	},
	{
		"address" : "Ub9Utbs3hHMharWZBenvU8TjbygAXNtD5L",
		"available" : 160000,
		"confirmed" : 160000,
		"frozen" : 0,
		"received" : 160000,
		"unspent" : 160000
	}
]

tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli sendto -c UWeSjd1ve5AZ14EVEKLfRYpuzApoauzLSV -f 20000 -m 交易20000 yujiali3 123456 UVjsbgzEQZqqN3sM3MXrHwjvQ1MQggiXf9 20000
{
	"hash" : "78f6ff90dad8ee124832b427c832e81914eeafd04af32cc8fd54cfc3af3a8dc2",
	"inputs" : 
	[

tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli showbalances yujiali3 123456
[
	{
		"address" : "UWeSjd1ve5AZ14EVEKLfRYpuzApoauzLSV",
		"available" : 0,
		"confirmed" : 0,
		"frozen" : 0,
		"received" : 0,
		"unspent" : 0
	},
	{
		"address" : "UVjsbgzEQZqqN3sM3MXrHwjvQ1MQggiXf9",
		"available" : 20000,
		"confirmed" : 20000,
		"frozen" : 0,
		"received" : 20000,
		"unspent" : 20000
	},
	{
		"address" : "Ub9Utbs3hHMharWZBenvU8TjbygAXNtD5L",
		"available" : 120000,
		"confirmed" : 120000,
		"frozen" : 0,
		"received" : 160000,
		"unspent" : 120000
	}
]

**Comment by o-u-p** [comment]
No problem detected,  please check out @yuyuyu2018 .

**Comment by yuyuyu2018** [comment]
You have to look at output in terms of hash value
