### ISSUE TITLE
after import key  address error 【bug】

### ISSUE THREAD

**Issue by snake0126** [UCHAIN-WORLD/uchain-fullnode#73]
[root@localhost uccli]# uc-cli importkeyfile --FILE /root/.UChain/uc-htmls/keys/uc_keystore_snake.json --ACCOUNTAUTH 1234 --ACCOUNTNAME snake
{
	"addresses" : 
	[
		"UNs1cAVCoVe952V544YGqnJrqp6vpDm1rN",
		"UkD2LLWDszMcvWAbBkre6i7iEtbyKHmkZ8",
		"UcaYYGwthBPBEcUztk4hJ2p2LjAZiPVP2r",
		"UPqb2AfKPpfqFoxAaujmH7Ay3CiGQgue7h"
	],
	"name" : "snake"
}

**Comment by snake0126** [comment]
{
	"address_count" : 5,
	"mnemonic" : "seven hour whisper coconut penalty amazing elite tank resource huge quote evidence alarm slush liar pottery first toilet blanket potato pink episode people boil",
	"name" : "snake"
}

**Comment by o-u-p** [comment]
Should be fixed in dev_tony2, please start testing @yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been proved that it has been solved.
