### ISSUE TITLE
Incapable of entering a block【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#74]
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli startmining -a UWeVjsMSNHboXVvKgz31sgRSVkEXeNCz6v tony1 123456
{
	"code" : 1024,
	"message" : "Currently mining, please use command <stopmining> to stop the running mining."
}

**Comment by o-u-p** [comment]
please start testing @yuyuyu2018 .

**Comment by yuyuyu2018** [comment]
An address can be blocked normally
