### ISSUE TITLE
The - M parameter in the sendtomulti command can also be successfully traded with other account addresses【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#77]
uc-cli sendtomulti -r UWeSjd1ve5AZ14EVEKLfRYpuzApoauzLSV:20000 -m UcfJL2f9ZZsxv9wY5eum1WXa3mTP2JhfyT tony1 123456
 
but  UcfJL2f9ZZsxv9wY5eum1WXa3mTP2JhfyT  this  address in the yujiali account.
Then UWeSjd1ve5AZ14EVEKLfRYpuzApoauzLSV the address receives the money.

**Comment by o-u-p** [comment]
It should be fixed,  please start testing @yuyuyu2018

**Comment by yuyuyu2018** [comment]
sendto there is also this problem.

**Comment by yangguanglu** [comment]
fixed f3bf5cd278908b9f1f61f46a9a84c2c2ec9ef224 @yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
