### ISSUE TITLE
 received fields are not displayed【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#79]
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli sendfrom tony1 123456 UWeVjsMSNHboXVvKgz31sgRSVkEXeNCz6v 3GidqrwT13H5zq7H99hkJHXYsS4UUoJ7NH  60000
 
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli showbalances tony1 123456
[
	{
		"address" : "3GidqrwT13H5zq7H99hkJHXYsS4UUoJ7NH",
		"available" : 30000,
		"confirmed" : 30000,
		"frozen" : 0,
		"received" : 90000,
		"unspent" : 30000
	},
	{

**Comment by o-u-p** [comment]
Cannot reproduce @yuyuyu2018

**Comment by yuyuyu2018** [comment]
Can't reproduce, close first
