### ISSUE TITLE
sendto command prompt error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#83]
tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli showbalances yujiali4 123456
[
	{
		"address" : "35hUA2CWfJVpHtzugqHL2VUC2zGUyWbst8",
		"available" : 60000,
		"confirmed" : 60000,
		"frozen" : 0,
		"received" : 60000,
		"unspent" : 60000
	},
	{
		"address" : "UaeG98wu548vYTYTogvEevVPuC6ToUST3z",
		"available" : 0,
		"confirmed" : 0,
		"frozen" : 0,
		"received" : 149999,
		"unspent" : 0
	}
]

tony@ubuntu:~/uchain-fullnode/build/bin$ uc-cli sendto -c 35hUA2CWfJVpHtzugqHL2VUC2zGUyWbst8 yujiali4  123456 UaeG98wu548vYTYTogvEevVPuC6ToUST3z 40000
{
	"code" : 5302,
	"message" : "not enough ucn or token in from address, or you do not own the from address!"
}

**Comment by yangguanglu** [comment]
5a07cc9bbd35d17a56f83644f0049e71a8229a1f fixed

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
