### ISSUE TITLE
Block reporting error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#84]
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong
20181123T000610 INFO [blockchain] Block [2885] verify (2) txs and (2) inputs
20181123T000610 INFO [blockchain] Block [2885] unverified in (0) secs or (0) ms/input
20181123T000610 ERROR [consensus] store_block error: coinage reward coinbase value is wrong

**Comment by yangguanglu** [comment]
fixed e051cdd3c41f0c4e54c8f881afed2b1c3d539097 @yuyuyu2018

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
