### ISSUE TITLE
if someone has voted or mined,sendfrom may cause ucd crash[bug]

### ISSUE THREAD

**Issue by yangguanglu** [UCHAIN-WORLD/uchain-fullnode#87]
Yangs-MacBook-Pro:bin cary$ ./uc-cli showbalances yang 123456
[
        {
                "address" : "UXFQvGKWh8GzEtV1RNw2Vo1abnynPy58u1",
                "available" : 0,
                "confirmed" : 50010000,
                "frozen" : 50010000,
                "received" : 50010000,
                "unspent" : 50010000
        },
        {
                "address" : "UiyoSgUnCbfSFVKcufwMZALVMURmiEfswq",
                "available" : 0,
                "confirmed" : 0,
                "frozen" : 0,
                "received" : 0,
                "unspent" : 0
        },
        {
                "address" : "UTg5BtZmFAvV8FaDQUw6BxRVphvyw6QhqF",
                "available" : 0,
                "confirmed" : 0,
                "frozen" : 0,
                "received" : 0,
                "unspent" : 0
        },
        {
                "address" : "UkRYvsnfJkwSTAUCcZnqCK8sE1ZYJP6so7",
                "available" : 0,
                "confirmed" : 0,
                "frozen" : 0,
                "received" : 0,
                "unspent" : 0
        },
        {
                "address" : "UNfrtAxhJRi83PjTPjV3yNPKnjLYR22Bhx",
                "available" : 81999999949990000,
                "confirmed" : 81999999949990000,
                "frozen" : 0,
                "received" : 163999999949990000,
                "unspent" : 81999999949990000
        }
]
Yangs-MacBook-Pro:bin cary$ ./uc-cli sendfrom yang 123456 UkRYvsnfJkwSTAUCcZnqCK8sE1ZYJP6so7 UiyoSgUnCbfSFVKcufwMZALVMURmiEfswq 100
{
        "code" : 3302,
        "message" : "not enough balance, unspent = 0, payment = 10100"
}
Yangs-MacBook-Pro:bin cary$ ./uc-cli sendfrom yang 123456 UXFQvGKWh8GzEtV1RNw2Vo1abnynPy58u1 UiyoSgUnCbfSFVKcufwMZALVMURmiEfswq 100

Yangs-MacBook-Pro:bin cary$ ./ucd
20181126T135122 INFO [ucd] Ucd version is 0.0.2
20181126T135122 INFO [ucd] Using config file: "/Users/cary/Library/Application Support/UChain/uc.conf"
20181126T135122 INFO [ucd] Please wait while the server is starting...
20181126T135122 INFO [node] Starting manual session.
20181126T135122 INFO [ucd] Seeding is complete.
20181126T135122 INFO [http] Http Service listen on 0.0.0.0:8820
20181126T135122 INFO [mgserver] Websocket Service listen on 0.0.0.0:8821
20181126T135122 INFO [node] Node start height is (514).
20181126T135122 INFO [node] Starting inbound session.
20181126T135122 INFO [node] Starting outbound session.
20181126T135122 INFO [ucd] Bound public query service to tcp://*:18707
20181126T135122 INFO [ucd] Server is started.
20181126T135130 INFO [upnp] No valid UPnP IGDs found
Assertion failed: (ucn_amount == 0), function sync_fetchutxo, file /Users/cary/Projects/uchain-fullnode/src/UChainService/api/command/base_helper.cpp, line 764.
20181126T135501 INFO [ucd] Stop signal detected (code: 6).
20181126T135501 INFO [ucd] Please wait while the server is stopping...
Abort trap: 6

**Comment by yangguanglu** [comment]
@yuyuyu2018 10773ee494b67be941b1757fd3ad853b7d070486

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
