### ISSUE TITLE
sendtomulti command must be executed with the - M parameter【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#88]
root@ubuntu:/home/tony/uchain-fullnode/build/bin# uc-cli sendtomulti -h

Usage: uc-cli sendtomulti [-h] --receivers value [--fee value]           
[--mychange value] ACCOUNTNAME ACCOUNTAUTH                               

Info: send ucn to multi target.                                          

Options (named):

-h [--help]          Send to more target.                                
-f [--fee]           Transaction fee. defaults to 10000 UCN bits         
-m [--mychange]      Change to this uid/address                          
-r [--receivers]     Send to [uid/address:ucn_bits].                     

Arguments (positional):

ACCOUNTNAME          Account name required.                              
ACCOUNTAUTH          Account password(authorization) required. 

root@ubuntu:/home/tony/uchain-fullnode/build/bin# uc-cli sendtomulti -r Ub9Utbs3hHMharWZBenvU8TjbygAXNtD5L:10000000 yang 123456
{
	"code" : 3002,
	"message" : "change address not belongs to you."
}

**Comment by yangguanglu** [comment]
fixed b4be80266c7d2c6690829a69d659101eca78d654

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
