### ISSUE TITLE
Block reporting error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#90]
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range
20181127T114650 ERROR [consensus] store_block error: fees are out of range

./uc-cli sendtomulti -r UaeG98wu548vYTYTogvEevVPuC6ToUST3z:90000000 yang 123456

[root@localhost bin]# ./uc-cli showmemorypool
[
	{
		"hash" : "defa22379b0da2492a037ac3f38de033ebbfd72295a592b12414ff454cf638f7",
		"inputs" : 
		[
			{
				"address" : "UNfrtAxhJRi83PjTPjV3yNPKnjLYR22Bhx",
				"previous_output" : 
				{
					"hash" : "56e0ad1f4209e1168fcc1faf637d47ec913b1da53e2d50a41d60f6a6541f574a",
					"index" : 0
				},
				"script" : "[ 304402201e42d381587e9c6ad75ebe5fab72b8daf4c835eaf425e4d7f268d65f6c55e47902203689014f4aca0e3a492a4f1406ad36a9c25a55f3f98cef1d51b45922d8d22e8e01 ] [ 027c99068f735e53064682b9ef1f548a00191b5ffb2fd9b9c8f32cde97793a0ed4 ]",
				"sequence" : 4294967295
			}
		],
		"lock_time" : "0",
		"outputs" : 
		[
			{
				"address" : "UaeG98wu548vYTYTogvEevVPuC6ToUST3z",
				"asset" : 
				{
					"type" : "ucn"
				},
				"index" : 0,
				"locked_height_range" : 0,
				"script" : "dup hash160 [ 8add2846945428902bfbd94e063023f6cee7062d ] equalverify checksig",
				"value" : 90000000
			},
			{
				"address" : "UNfrtAxhJRi83PjTPjV3yNPKnjLYR22Bhx",
				"asset" : 
				{
					"type" : "ucn"
				},
				"index" : 1,
				"locked_height_range" : 0,
				"script" : "dup hash160 [ 078910a58cea508623e2be9b38beb6e7d576e880 ] equalverify checksig",
				"value" : 81999999909990000
			}
		],
		"version" : "4"
	}
]

**Comment by yangguanglu** [comment]
fixed b7bcba8fe6036703b4cec18a8e09481a736df508

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
