### ISSUE TITLE
sendtokento and sendtokenfrom command execution failed【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#91]
[root@localhost bin]# ./uc-cli sendtokento snake02 123456 UaeG98wu548vYTYTogvEevVPuC6ToUST3z BLOCK 65 
{
	"code" : 5304,
	"message" : "validate transaction failure"
}

[root@localhost bin]# ./uc-cli sendtokenfrom snake02 123456 UcuW7wVu198Nuzok8eeMDUNEZQoGqQRRz5  UaeG98wu548vYTYTogvEevVPuC6ToUST3z BLOCK 65 
{
	"code" : 5304,
	"message" : "validate transaction failure"
}

**Comment by yangguanglu** [comment]
fixed 98cb1bcc88e400cd39785bbd1b3be230e0b37103

**Comment by yuyuyu2018** [comment]
当自己是矿工时，不能发token

**Comment by yuyuyu2018** [comment]
When you're a miner, you can't make token.
