### ISSUE TITLE
sendtokento and sendtokenfrom command prompt error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#92]
[root@localhost bin]# ./uc-cli sendtokento yujiali4 123456 Ub9Utbs3hHMharWZBenvU8TjbygAXNtD5L VOTE 1
{
	"code" : 5304,
	"message" : "validate transaction failure"
}

[root@localhost bin]# ./uc-cli sendtokenfrom  yujiali4 123456 UaeG98wu548vYTYTogvEevVPuC6ToUST3z  Ub9Utbs3hHMharWZBenvU8TjbygAXNtD5L VOTE 1
{
	"code" : 5304,
	"message" : "validate transaction failure"
}

**Comment by yangguanglu** [comment]
fixed 10773ee494b67be941b1757fd3ad853b7d070486

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
