### ISSUE TITLE
When token is issued, the signrawtx command fails to execute【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#96]
[root@localhost bin]# ./uc-cli createrawtx -r UaeG98wu548vYTYTogvEevVPuC6ToUST3z:32 -s UcuW7wVu198Nuzok8eeMDUNEZQoGqQRRz5 -n BLOCK -t 3
0400000002a57efce617e7b8ab49a9e94fb9a0e080d21ce3153b292e45c5d4dbc2305c33340000000000ffffffffa9166ecfa24c0352c3acce1740b478289f8645033d511d7d8c5e24b5707e3f940200000000ffffffff0300000000000000001976a9148add2846945428902bfbd94e063023f6cee7062d88ac01000000020000000200000005424c4f434b2000000000000000e0eb1302000000001976a914a3af5154c2ee7f294f00e285cdb9489d8cfc830588ac010000000000000000000000000000001976a914a3af5154c2ee7f294f00e285cdb9489d8cfc830588ac01000000020000000200000005424c4f434b6e1a00000000000000000000

[root@localhost bin]# ./uc-cli decoderawtx 0400000002a57efce617e7b8ab49a9e94fb9a0e080d21ce3153b292e45c5d4dbc2305c33340000000000ffffffffa9166ecfa24c0352c3acce1740b478289f8645033d511d7d8c5e24b5707e3f940200000000ffffffff0300000000000000001976a9148add2846945428902bfbd94e063023f6cee7062d88ac01000000020000000200000005424c4f434b2000000000000000e0eb1302000000001976a914a3af5154c2ee7f294f00e285cdb9489d8cfc830588ac010000000000000000000000000000001976a914a3af5154c2ee7f294f00e285cdb9489d8cfc830588ac01000000020000000200000005424c4f434b6e1a00000000000000000000
{
	"hash" : "78c807e54e707c03a5e9a070f49cd1d2e2fffc7bd81f51beffd767555f3261a1",
	"inputs" : 
	[
		{
			"previous_output" : 
			{
				"hash" : "34335c30c2dbd4c5452e293b15e31cd280e0a0b94fe9a949abb8e717e6fc7ea5",
				"index" : 0
			},
			"script" : "",
			"sequence" : 4294967295
		},
		{
			"previous_output" : 
			{
				"hash" : "943f7e70b5245e8c7d1d513d0345869f2878b44017ceacc352034ca2cf6e16a9",
				"index" : 2
			},
			"script" : "",
			"sequence" : 4294967295
		}
	],
	"lock_time" : "0",
	"outputs" : 
	[
		{
			"address" : "UaeG98wu548vYTYTogvEevVPuC6ToUST3z",
			"asset" : 
			{
				"quantity" : 32,
				"symbol" : "BLOCK",
				"type" : "token-transfer"
			},
			"index" : 0,
			"locked_height_range" : 0,
			"script" : "dup hash160 [ 8add2846945428902bfbd94e063023f6cee7062d ] equalverify checksig",
			"value" : 0
		},
		{
			"address" : "UcuW7wVu198Nuzok8eeMDUNEZQoGqQRRz5",
			"asset" : 
			{
				"type" : "ucn"
			},
			"index" : 1,
			"locked_height_range" : 0,
			"script" : "dup hash160 [ a3af5154c2ee7f294f00e285cdb9489d8cfc8305 ] equalverify checksig",
			"value" : 34860000
		},
		{
			"address" : "UcuW7wVu198Nuzok8eeMDUNEZQoGqQRRz5",
			"asset" : 
			{
				"quantity" : 6766,
				"symbol" : "BLOCK",
				"type" : "token-transfer"
			},
			"index" : 2,
			"locked_height_range" : 0,
			"script" : "dup hash160 [ a3af5154c2ee7f294f00e285cdb9489d8cfc8305 ] equalverify checksig",
			"value" : 0
		}
	],
	"version" : "4"
}

[root@localhost bin]# ./uc-cli signrawtx snake02 123456 0400000002a57efce617e7b8ab49a9e94fb9a0e080d21ce3153b292e45c5d4dbc2305c33340000000000ffffffffa9166ecfa24c0352c3acce1740b478289f8645033d511d7d8c5e24b5707e3f940200000000ffffffff0300000000000000001976a9148add2846945428902bfbd94e063023f6cee7062d88ac01000000020000000200000005424c4f434b2000000000000000e0eb1302000000001976a914a3af5154c2ee7f294f00e285cdb9489d8cfc830588ac010000000000000000000000000000001976a914a3af5154c2ee7f294f00e285cdb9489d8cfc830588ac01000000020000000200000005424c4f434b6e1a00000000000000000000
{
	"code" : 5304,
	"message" : "validate transaction failure"
}

**Comment by yangguanglu** [comment]
fixed 17fe31f0c5145539c58b08f6bd9522c27a773a1f @yuyuyu2018 not allow to send block token in this way

**Comment by yuyuyu2018** [comment]
It has been verified and solved.
