### ISSUE TITLE
Mining error【bug】

### ISSUE THREAD

**Issue by yuyuyu2018** [UCHAIN-WORLD/uchain-fullnode#97]
20181128T151317 WARNING [blockchain] orphan_chain.empty()
20181128T151317 WARNING [node] Error storing block from [192.168.16.211:35246] validation of inputs failed
20181128T151325 WARNING [blockchain] Double spend attempt.
20181128T151325 WARNING [blockchain] Invalid input [e8e8592ffd34244e191992654f5831093f05d7ff32b5c2c62e35b14b50ff7e5c:0]
20181128T151325 WARNING [blockchain] Invalid block [bc4eddd62ae0cd3dc24736cf5836fdb8f987e7e84ba652902661f0aa9bc2bc1c] validation of inputs failed
20181128T151325 WARNING [blockchain] orphan_chain.empty()
20181128T151325 WARNING [node] Error storing block from [192.168.16.211:5682] validation of inputs failed
20181128T151326 WARNING [blockchain] Double spend attempt.
20181128T151326 WARNING [blockchain] Invalid input [e8e8592ffd34244e191992654f5831093f05d7ff32b5c2c62e35b14b50ff7e5c:0]
20181128T151326 WARNING [blockchain] Invalid block [bc4eddd62ae0cd3dc24736cf5836fdb8f987e7e84ba652902661f0aa9bc2bc1c] validation of inputs failed
20181128T151326 WARNING [blockchain] orphan_chain.empty()
20181128T151326 WARNING [node] Error storing block from [192.168.16.211:35410] validation of inputs failed
20181128T151334 WARNING [blockchain] Double spend attempt.
20181128T151334 WARNING [blockchain] Invalid input [e8e8592ffd34244e191992654f5831093f05d7ff32b5c2c62e35b14b50ff7e5c:0]
20181128T151334 WARNING [blockchain] Invalid block [bc4eddd62ae0cd3dc24736cf5836fdb8f987e7e84ba652902661f0aa9bc2bc1c] validation of inputs failed
20181128T151334 WARNING [blockchain] orphan_chain.empty()
20181128T151334 WARNING [node] Error storing block from [192.168.16.211:35584] validation of inputs failed
20181128T151334 WARNING [blockchain] Double spend attempt.
20181128T151334 WARNING [blockchain] Invalid input [e8e8592ffd34244e191992654f5831093f05d7ff32b5c2c62e35b14b50ff7e5c:0]
20181128T151334 WARNING [blockchain] Invalid block [bc4eddd62ae0cd3dc24736cf5836fdb8f987e7e84ba652902661f0aa9bc2bc1c] validation of inputs failed
20181128T151334 WARNING [blockchain] orphan_chain.empty()
20181128T151334 WARNING [node] Error storing block from [192.168.16.211:5682] validation of inputs failed
20181128T154349 WARNING [network] Reseeding finished, but got address list: 1, less than seed count: 1, roll back the hosts cache.
20181128T154401 ERROR [node] Blockchain failed to start.
20181128T154401 ERROR [ucd] Server failed to start with error, operation failed.

**Comment by yangguanglu** [comment]
fixed 4ab968f0061685e6a761b130bd5560f50b5a8cf5 @yuyuyu2018

**Comment by yuyuyu2018** [comment]
Delete the mainner, restart it is good
